### ISSUE TITLE
SkyBlock expansion failed to load

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#110]
Spigot 1.15.1 (Jenkins 2554)
CombatLogX 10.0.0.0.Beta-82
BentoBox 1.10.1-SNAPSHOT-b1558
BSkyBlock 1.10.1-SNAPSHOT-b583

**Describe the bug**
SkyBlock expansion failed to load on server start-up.

**To Reproduce**
- Update to CombatLogX 10.0.0.0.Beta-82
- Add SkyBlock expansion to the mix
- Start server
- Encounter error
```
[22:02:03] [Server thread/INFO]: [CombatLogX] Loading CombatLogX v10.0.0.0.Beta-82
[22:02:03] [Server thread/ERROR]: [CombatLogX] Failed to load an expansion.
java.lang.NullPointerException: null
        at java.lang.String.replace(String.java:2143) ~[?:?]
        at com.SirBlobman.combatlogx.api.expansion.ExpansionManager.loadExpansion(ExpansionManager.java:188) [CombatLogX-10.0.0.0.Beta-82.jar:?]
        at com.SirBlobman.combatlogx.api.expansion.ExpansionManager.checkFileForExpansion(ExpansionManager.java:130) [CombatLogX-10.0.0.0.Beta-82.jar:?]
        at com.SirBlobman.combatlogx.api.expansion.ExpansionManager.loadExpansions(ExpansionManager.java:39) [CombatLogX-10.0.0.0.Beta-82.jar:?]
        at com.SirBlobman.combatlogx.CombatLogX.onLoad(CombatLogX.java:64) [CombatLogX-10.0.0.0.Beta-82.jar:?]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:356) [spigot-1.15.1.jar-2020-01-03-1758:git-Spigot-492a779-e7202cd]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:202) [spigot-1.15.1.jar-2020-01-03-1758:git-Spigot-492a779-e7202cd]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783) [spigot-1.15.1.jar-2020-01-03-1758:git-Spigot-492a779-e7202cd]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Minecraft Version**
**CombatLogX Version:**
```
>clx version
[22:10:38] [Craft Scheduler Thread - 17/INFO]: Server Version: git-Spigot-492a779-e7202cd (MC: 1.15.1)
[22:10:38] [Craft Scheduler Thread - 17/INFO]: Bukkit Version: 1.15.1-R0.1-SNAPSHOT
[22:10:38] [Craft Scheduler Thread - 17/INFO]: Minecraft Version: 1.15.1
[22:10:38] [Craft Scheduler Thread - 17/INFO]: NMS Version: 1_15_R1
[22:10:38] [Craft Scheduler Thread - 17/INFO]: 
[22:10:38] [Craft Scheduler Thread - 17/INFO]: CombatLogX by SirBlobman
[22:10:38] [Craft Scheduler Thread - 17/INFO]: Installed Version: v10.0.0.0.Beta
[22:10:38] [Craft Scheduler Thread - 17/INFO]: Latest Version: vUpdate Checker Disabled!
[22:10:38] [Craft Scheduler Thread - 17/INFO]: 
[22:10:38] [Craft Scheduler Thread - 17/INFO]: Getting expansion versions...
[22:10:38] [Craft Scheduler Thread - 17/INFO]: 
[22:10:38] [Craft Scheduler Thread - 17/INFO]:   Residence Compatibility v15.0
[22:10:38] [Craft Scheduler Thread - 17/INFO]:   Citizens Compatibility v15.0
[22:10:38] [Craft Scheduler Thread - 17/INFO]:   PlaceholderAPI Compatibility v15.0
[22:10:38] [Craft Scheduler Thread - 17/INFO]:   WorldGuard Compatibility v15.0
[22:10:38] [Craft Scheduler Thread - 17/INFO]:   Logger v15.0
[22:10:38] [Craft Scheduler Thread - 17/INFO]:   Damage Tagger v15.0
[22:10:38] [Craft Scheduler Thread - 17/INFO]:   Notifier v15.0
```

**Comment by SirBlobman** [comment]
Thanks for the report, I'll check it out :)

**Comment by SirBlobman** [comment]
Should be fixed on build 83

**Comment by SlimeDog** [comment]
Confirmed no load error with build 83. I haven't tested functionality yet.
