### ISSUE TITLE
EventException due to IncompatibleClassChangeError

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#112]
**Describe the bug**
EventException due to IncompatibleClassChangeError. Log (appended) shows a conflict with Residence. I was not in a Residence-defined area. No errors display in-game.

**To Reproduce**
Fell into poisoned water (poison supplied by PyroWeatherPro). Took damage.

**Expected behavior**
No error

**Screenshots**

**Minecraft Version**
**CombatLogX Version:**
```
>clx version
[08:53:53] [Server thread/INFO]: Getting version information for CombatLogX...
[08:53:53] [Craft Scheduler Thread - 28/INFO]: 
[08:53:53] [Craft Scheduler Thread - 28/INFO]: Server Version: git-Spigot-800b93f-596b0b2 (MC: 1.15.2)
[08:53:53] [Craft Scheduler Thread - 28/INFO]: Bukkit Version: 1.15.2-R0.1-SNAPSHOT
[08:53:53] [Craft Scheduler Thread - 28/INFO]: Minecraft Version: 1.15.2
[08:53:53] [Craft Scheduler Thread - 28/INFO]: NMS Version: 1_15_R1
[08:53:53] [Craft Scheduler Thread - 28/INFO]: 
[08:53:53] [Craft Scheduler Thread - 28/INFO]: CombatLogX by SirBlobman
[08:53:53] [Craft Scheduler Thread - 28/INFO]: Installed Version: v10.0.0.0.Beta
[08:53:53] [Craft Scheduler Thread - 28/INFO]: Latest Version: vUpdate Checker Disabled!
[08:53:53] [Craft Scheduler Thread - 28/INFO]: 
[08:53:53] [Craft Scheduler Thread - 28/INFO]: Getting expansion versions...
[08:53:53] [Craft Scheduler Thread - 28/INFO]: 
[08:53:53] [Craft Scheduler Thread - 28/INFO]:   Residence Compatibility v15.0
[08:53:53] [Craft Scheduler Thread - 28/INFO]:   Citizens Compatibility v15.0
[08:53:53] [Craft Scheduler Thread - 28/INFO]:   PlaceholderAPI Compatibility v15.0
[08:53:53] [Craft Scheduler Thread - 28/INFO]:   WorldGuard Compatibility v15.0
[08:53:53] [Craft Scheduler Thread - 28/INFO]:   Logger v15.0
[08:53:53] [Craft Scheduler Thread - 28/INFO]:   Damage Tagger v15.0
[08:53:53] [Craft Scheduler Thread - 28/INFO]:   Notifier v15.0
```

**Additional context**
```
[08:49:07] [Server thread/ERROR]: Could not pass event PlayerTagEvent to CombatLogX v10.0.0.0.Beta-104
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at com.SirBlobman.combatlogx.utility.CombatManager.tag(CombatManager.java:47) ~[?:?]
        at com.SirBlobman.combatlogx.expansion.damage.tagger.listener.ListenerDamage.onDamage(ListenerDamage.java:65) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor248.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:230) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:923) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:905) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:766) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:955) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity0(EntityLiving.java:1624) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity0(EntityHuman.java:862) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1028) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity(EntityHuman.java:785) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.EntityPlayer.damageEntity(EntityPlayer.java:659) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:258) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:245) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at me.surrend3r.nofall.listeners.FallDamageListener.onFall(FallDamageListener.java:30) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor233.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:230) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:923) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:905) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:766) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:955) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity0(EntityLiving.java:1624) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity0(EntityHuman.java:862) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1028) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity(EntityHuman.java:785) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.EntityPlayer.damageEntity(EntityPlayer.java:659) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.EntityLiving.b(EntityLiving.java:1463) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.EntityHuman.b(EntityHuman.java:1633) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.Block.fallOn(Block.java:592) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.Entity.a(Entity.java:1027) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.EntityLiving.a(EntityLiving.java:226) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.EntityPlayer.a(EntityPlayer.java:1012) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1028) ~[?:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.bekvon.bukkit.residence.api.ResidenceInterface, but class was expected
        at com.SirBlobman.combatlogx.expansion.compatibility.residence.hook.HookResidence.isSafeZone(HookResidence.java:16) ~[?:?]
        at com.SirBlobman.combatlogx.expansion.compatibility.residence.handler.ResidenceNoEntryHandler.isSafeZone(ResidenceNoEntryHandler.java:28) ~[?:?]
        at com.SirBlobman.combatlogx.api.expansion.noentry.NoEntryForceFieldListener.isSafe(NoEntryForceFieldListener.java:24) ~[?:?]
        at com.SirBlobman.combatlogx.api.olivolja3.force.field.ForceField.onTag(ForceField.java:221) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.2.jar-2020-01-24-0035:git-Spigot-800b93f-596b0b2]
        ... 62 more
```

**Comment by SirBlobman** [comment]
Should be fixed
