### ISSUE TITLE
ClassNotFoundException on shutdown

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#114]
**Describe the bug**
ERROR on server shutdown

**To Reproduce**
- Install CombatLogX
- Start server
- Shutdown server
- Read console/log

**Minecraft Version**
> 1.15.2 (Jenkins 2627)

**CombatLogX Version:**
```
>clx version
[09:02:10] [Server thread/INFO]: Getting version information for CombatLogX...
[09:02:10] [Craft Scheduler Thread - 30/INFO]: 
[09:02:10] [Craft Scheduler Thread - 30/INFO]: Server Version: git-Spigot-c574e08-d171d7e (MC: 1.15.2)
[09:02:10] [Craft Scheduler Thread - 30/INFO]: Bukkit Version: 1.15.2-R0.1-SNAPSHOT
[09:02:10] [Craft Scheduler Thread - 30/INFO]: Minecraft Version: 1.15.2
[09:02:10] [Craft Scheduler Thread - 30/INFO]: NMS Version: 1_15_R1
[09:02:10] [Craft Scheduler Thread - 30/INFO]: 
[09:02:10] [Craft Scheduler Thread - 30/INFO]: CombatLogX by SirBlobman
[09:02:10] [Craft Scheduler Thread - 30/INFO]: Installed Version: v10.0.0.0.Beta
[09:02:10] [Craft Scheduler Thread - 30/INFO]: Latest Version: vUpdate Checker Disabled!
[09:02:10] [Craft Scheduler Thread - 30/INFO]: 
[09:02:10] [Craft Scheduler Thread - 30/INFO]: Getting expansion versions...
[09:02:10] [Craft Scheduler Thread - 30/INFO]: 
[09:02:10] [Craft Scheduler Thread - 30/INFO]:   Residence Compatibility v15.0
[09:02:10] [Craft Scheduler Thread - 30/INFO]:   Citizens Compatibility v15.0
[09:02:10] [Craft Scheduler Thread - 30/INFO]:   PlaceholderAPI Compatibility v15.0
[09:02:10] [Craft Scheduler Thread - 30/INFO]:   WorldGuard Compatibility v15.0
[09:02:10] [Craft Scheduler Thread - 30/INFO]:   Logger v15.0
[09:02:10] [Craft Scheduler Thread - 30/INFO]:   Damage Tagger v15.0
[09:02:10] [Craft Scheduler Thread - 30/INFO]:   Notifier v15.0
```

```
[08:58:40] [Server thread/INFO]: [CombatLogX] Disabling CombatLogX v10.0.0.0.Beta-127
[08:58:40] [Server thread/ERROR]: Error occurred while disabling CombatLogX v10.0.0.0.Beta-127 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
        at com.SirBlobman.combatlogx.api.shaded.nms.NMS_1_8_R1.<init>(NMS_1_8_R1.java:4) ~[?:?]
        at com.SirBlobman.combatlogx.api.shaded.nms.NMS_1_9_R1.<init>(NMS_1_9_R1.java:9) ~[?:?]
        at com.SirBlobman.combatlogx.api.shaded.nms.NMS_1_12_R1.<init>(NMS_1_12_R1.java:3) ~[?:?]
        at com.SirBlobman.combatlogx.api.shaded.nms.NMS_1_13_R1.<init>(NMS_1_13_R1.java:3) ~[?:?]
        at com.SirBlobman.combatlogx.api.shaded.nms.NMS_1_15_R1.<init>(NMS_1_15_R1.java:3) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at java.lang.Class.newInstance(Class.java:584) ~[?:?]
        at com.SirBlobman.combatlogx.api.shaded.nms.NMS_Handler.getHandler(NMS_Handler.java:65) ~[?:?]
        at com.SirBlobman.combatlogx.expansion.notifier.utility.ActionBarManager.removeActionBar(ActionBarManager.java:59) ~[?:?]
        at com.SirBlobman.combatlogx.expansion.notifier.Notifier.onDisable(Notifier.java:71) ~[?:?]
        at com.SirBlobman.combatlogx.api.expansion.ExpansionManager.disableExpansions(ExpansionManager.java:86) ~[?:?]
        at com.SirBlobman.combatlogx.CombatLogX.onDisable(CombatLogX.java:83) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.15.2.jar-2020-02-10-2322:git-Spigot-c574e08-d171d7e]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376) [spigot-1.15.2.jar-2020-02-10-2322:git-Spigot-c574e08-d171d7e]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453) [spigot-1.15.2.jar-2020-02-10-2322:git-Spigot-c574e08-d171d7e]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:445) [spigot-1.15.2.jar-2020-02-10-2322:git-Spigot-c574e08-d171d7e]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:398) [spigot-1.15.2.jar-2020-02-10-2322:git-Spigot-c574e08-d171d7e]
        at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:699) [spigot-1.15.2.jar-2020-02-10-2322:git-Spigot-c574e08-d171d7e]
        at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:696) [spigot-1.15.2.jar-2020-02-10-2322:git-Spigot-c574e08-d171d7e]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:864) [spigot-1.15.2.jar-2020-02-10-2322:git-Spigot-c574e08-d171d7e]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.15.2.jar-2020-02-10-2322:git-Spigot-c574e08-d171d7e]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.15.2.jar-2020-02-10-2322:git-Spigot-c574e08-d171d7e]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 24 more
```

**Comment by SirBlobman** [comment]
This should be fixed after the SirBlobmanAPI Update
(CombatLogX Build #139)
