### ISSUE TITLE
InvocationTargetException on startup

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#116]
CombatLogX v10.0.0.0.Beta-144 (you might want to include the build number in the **clx version** output)
```
>clx version
Getting version information for CombatLogX...
Server Version: git-Spigot-6de3d4b-a6f8093 (MC: 1.15.2)
Bukkit Version: 1.15.2-R0.1-SNAPSHOT
Minecraft Version: 1.15.2
NMS Version: 1_15_R1

CombatLogX by SirBlobman
Installed Version: v10.0.0.0.Beta
Latest Version: vUpdate Checker Disabled!
Getting expansion versions...
Residence Compatibility v15.0
Citizens Compatibility v15.0
PlaceholderAPI Compatibility v15.0
WorldGuard Compatibility v15.0
Mob Tagger v15.0
Logger v15.0
Damage Tagger v15.0
Notifier v15.0
```
On server start-up
```
[21:10:56] [Server thread/INFO]: Registering custom WorldGuard flags...
[21:10:56] [Server thread/ERROR]: Failed to find register flags method in 'com.SirBlobman.combatlogx.expansion.compatibility.worldguard.hook.HookWorldGuard_V7_0'.
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.SirBlobman.combatlogx.expansion.compatibility.worldguard.hook.HookWorldGuard$WorldGuardVersion.registerFlags(HookWorldGuard.java:32) [CLX-WorldGuard-10.0.0.0.Beta-134.jar:?]
        at com.SirBlobman.combatlogx.expansion.compatibility.worldguard.hook.HookWorldGuard.registerFlags(HookWorldGuard.java:117) [CLX-WorldGuard-10.0.0.0.Beta-134.jar:?]
        at com.SirBlobman.combatlogx.expansion.compatibility.worldguard.CompatibilityWorldGuard.onLoad(CompatibilityWorldGuard.java:54) [CLX-WorldGuard-10.0.0.0.Beta-134.jar:?]
        at com.SirBlobman.combatlogx.api.expansion.ExpansionManager.loadExpansion(ExpansionManager.java:192) [CombatLogX-10.0.0.0.Beta-144.jar:?]
        at com.SirBlobman.combatlogx.api.expansion.ExpansionManager.checkFileForExpansion(ExpansionManager.java:130) [CombatLogX-10.0.0.0.Beta-144.jar:?]
        at com.SirBlobman.combatlogx.api.expansion.ExpansionManager.loadExpansions(ExpansionManager.java:39) [CombatLogX-10.0.0.0.Beta-144.jar:?]
        at com.SirBlobman.combatlogx.CombatLogX.onLoad(CombatLogX.java:64) [CombatLogX-10.0.0.0.Beta-144.jar:?]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:358) [spigot-1.15.2.jar-2020-03-15-0649:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.15.2.jar-2020-03-15-0649:git-Spigot-6de3d4b-a6f8093]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar-2020-03-15-0649:git-Spigot-6de3d4b-a6f8093]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.sk89q.worldguard.protection.flags.registry.FlagConflictException: A flag already exists by the name no-tagging
        at com.sk89q.worldguard.protection.flags.registry.SimpleFlagRegistry.forceRegister(SimpleFlagRegistry.java:87) ~[?:?]
        at com.sk89q.worldguard.protection.flags.registry.SimpleFlagRegistry.register(SimpleFlagRegistry.java:63) ~[?:?]
        at com.SirBlobman.combatlogx.expansion.compatibility.worldguard.hook.HookWorldGuard_V7_0.registerFlags(HookWorldGuard_V7_0.java:34) ~[?:?]
        ... 15 more
[21:10:56] [Server thread/INFO]: Finished registering custom WorldGuard flags.
```
No change to configuration, and it happened on only one of two identical test servers. And
```
/clx reload
Successfully reloaded all configuration files from CombatLogX and expansions.
```

**Comment by SirBlobman** [comment]
Thanks for the info, I'll add a check for already registered flags.
