### ISSUE TITLE
Fatal ERROR on server start-up

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#117]
Fatal ERROR on server start-up
```
>clx ver
[21:38:14] [Server thread/INFO]: Getting version information for CombatLogX...
[21:38:14] [Craft Scheduler Thread - 35/INFO]: 
[21:38:14] [Craft Scheduler Thread - 35/INFO]: Server Version: git-Spigot-a03b1fd-5838285 (MC: 1.15.2)
[21:38:14] [Craft Scheduler Thread - 35/INFO]: Bukkit Version: 1.15.2-R0.1-SNAPSHOT
[21:38:14] [Craft Scheduler Thread - 35/INFO]: Minecraft Version: 1.15.2
[21:38:14] [Craft Scheduler Thread - 35/INFO]: NMS Version: 1_15_R1
[21:38:14] [Craft Scheduler Thread - 35/INFO]: 
[21:38:14] [Craft Scheduler Thread - 35/INFO]: CombatLogX by SirBlobman
[21:38:14] [Craft Scheduler Thread - 35/INFO]: Installed Version: v10.0.0.0.Beta-174
[21:38:14] [Craft Scheduler Thread - 35/INFO]: Latest Version: vUpdate Checker Disabled!
[21:38:14] [Craft Scheduler Thread - 35/INFO]: 
[21:38:14] [Craft Scheduler Thread - 35/INFO]: Getting expansion versions...
[21:38:14] [Craft Scheduler Thread - 35/INFO]: 
[21:38:14] [Craft Scheduler Thread - 35/INFO]:   Citizens Compatibility v15.0
[21:38:14] [Craft Scheduler Thread - 35/INFO]:   PlaceholderAPI Compatibility v15.0
[21:38:14] [Craft Scheduler Thread - 35/INFO]:   Residence Compatibility v15.0
[21:38:14] [Craft Scheduler Thread - 35/INFO]:   WorldGuard Compatibility v15.0
[21:38:14] [Craft Scheduler Thread - 35/INFO]:   Damage Tagger v15.0
[21:38:14] [Craft Scheduler Thread - 35/INFO]:   Logger v15.0
[21:38:14] [Craft Scheduler Thread - 35/INFO]:   Mob Tagger v15.0
[21:38:14] [Craft Scheduler Thread - 35/INFO]:   Notifier v15.1
```
```
[20:35:03] [Server thread/INFO]: [CombatLogX] Searching for a handler that matches NMS version 1_15_R1
[20:35:03] [Server thread/ERROR]: Fatal error trying to convert CombatLogX v10.0.0.0.Beta-174:com/SirBlobman/combatlogx/api/shaded/nms/ItemHandler_1_15_R1.class
org.bukkit.plugin.AuthorNagException: No legacy enum constant for PLAYER_HEAD. Did you forget to define a modern (1.13+) api-version in your plugin.yml?
        at org.bukkit.craftbukkit.v1_15_R1.util.Commodore$1$1.visitFieldInsn(Commodore.java:176) ~[spigot-1.15.2.jar-2020-04-05-0749:git-Spigot-a03b1fd-5838285]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.readCode(ClassReader.java:2419) ~[spigot-1.15.2.jar-2020-04-05-0749:git-Spigot-a03b1fd-5838285]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1492) ~[spigot-1.15.2.jar-2020-04-05-0749:git-Spigot-a03b1fd-5838285]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:717) ~[spigot-1.15.2.jar-2020-04-05-0749:git-Spigot-a03b1fd-5838285]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:401) ~[spigot-1.15.2.jar-2020-04-05-0749:git-Spigot-a03b1fd-5838285]
        at org.bukkit.craftbukkit.v1_15_R1.util.Commodore.convert(Commodore.java:130) ~[spigot-1.15.2.jar-2020-04-05-0749:git-Spigot-a03b1fd-5838285]
        at org.bukkit.craftbukkit.v1_15_R1.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:293) [spigot-1.15.2.jar-2020-04-05-0749:git-Spigot-a03b1fd-5838285]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:140) [spigot-1.15.2.jar-2020-04-05-0749:git-Spigot-a03b1fd-5838285]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) [spigot-1.15.2.jar-2020-04-05-0749:git-Spigot-a03b1fd-5838285]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) [?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) [?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:315) [?:?]
        at com.SirBlobman.combatlogx.api.shaded.nms.MultiVersionHandler.getInterfaceClass(MultiVersionHandler.java:53) [CombatLogX-10.0.0.0.Beta-174.jar:?]
        at com.SirBlobman.combatlogx.api.shaded.nms.MultiVersionHandler.setupInterface(MultiVersionHandler.java:27) [CombatLogX-10.0.0.0.Beta-174.jar:?]
        at com.SirBlobman.combatlogx.api.shaded.nms.MultiVersionHandler.<init>(MultiVersionHandler.java:14) [CombatLogX-10.0.0.0.Beta-174.jar:?]
        at com.SirBlobman.combatlogx.CombatLogX.<init>(CombatLogX.java:51) [CombatLogX-10.0.0.0.Beta-174.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) [?:?]
        at java.lang.Class.newInstance(Class.java:584) [?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) [spigot-1.15.2.jar-2020-04-05-0749:git-Spigot-a03b1fd-5838285]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) [spigot-1.15.2.jar-2020-04-05-0749:git-Spigot-a03b1fd-5838285]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) [spigot-1.15.2.jar-2020-04-05-0749:git-Spigot-a03b1fd-5838285]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) [spigot-1.15.2.jar-2020-04-05-0749:git-Spigot-a03b1fd-5838285]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:353) [spigot-1.15.2.jar-2020-04-05-0749:git-Spigot-a03b1fd-5838285]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:210) [spigot-1.15.2.jar-2020-04-05-0749:git-Spigot-a03b1fd-5838285]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar-2020-04-05-0749:git-Spigot-a03b1fd-5838285]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by SlimeDog** [comment]
Confirmed fixed in build 176. Thanks.
