### ISSUE TITLE
CombatLogX v10.0.0.0 Beta-219 "[Expansion Name] does not contain an expansion.yml file."

### ISSUE THREAD

**Issue by B-Knight49** [SirBlobman/CombatLogX#124]
**Describe the bug**
All expansions throw the following error on startup of the server:

> [13:11:32 ERROR]: [CombatLogX] An error occurred while trying to load an expansion
java.lang.IllegalStateException: Expansion file 'plugins/CombatLogX/expansions/Citizens Compatibility.jar' does not contain an expansion.yml file.
at com.SirBlobman.combatlogx.api.expansion.ExpansionManager.getExpansionDescription(ExpansionManager.java:254) ~[?:?]
at com.SirBlobman.combatlogx.api.expansion.ExpansionManager.loadExpansion(ExpansionManager.java:170) ~[?:?]
at com.SirBlobman.combatlogx.api.expansion.ExpansionManager.loadExpansions(ExpansionManager.java:71) ~[?:?]
at com.SirBlobman.combatlogx.CombatLogX.onLoad(CombatLogX.java:65) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:365) ~[patched_1.15.2.jar:git-Paper-298]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-298]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[patched_1.15.2.jar:git-Paper-298]
at java.lang.Thread.run(Thread.java:834) [?:?]

All expansions do have a expansion.yml file. 

**To Reproduce**
1 - Download Beta-219 here: https://ci.codemc.io/job/sirblobman/job/CombatLogX/219/
2 - Start server with the expansions that come with that download
3 - Errors

**Expected behavior**
Expansions load sucessfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/26165117/86278972-26b24e00-bbd1-11ea-9aba-1dabd7095601.png)

**Minecraft Version**
 - Paper-298 1.15.2

**CombatLogX Version:**
 - v10.0.0.0 Beta-219

**Additional context**
Add any other information about the problem here.

**Comment by SirBlobman** [comment]
Your expansion jar files are outdated, every expansion contains an `expansion.yml` file now.

**Comment by B-Knight49** [comment]
Weird. Must've been my FTP client fucking up. 

I definitely copied over the folder containing the expansions that were bundled with B219. But you're right, the expansion .jars never updated. 

My bad.
