### ISSUE TITLE
Console spamming errors

### ISSUE THREAD

**Issue by hasanas83V2001** [SirBlobman/CombatLogX#13]
Console it spamming errors and I'm not sure why it happens:
`[13:27:55 ERROR]: Could not pass event CombatTimerChangeEvent to CombatLogX v5.1.0 Release
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-edd0396-20ab5d3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-edd0396-20ab5d3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-edd0396-20ab5d3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-edd0396-20ab5d3]
        at com.SirBlobman.combatlogx.utility.Util.call(Util.java:176) [CombatLogX.jar:?]
        at com.SirBlobman.combatlogx.Combat.run(Combat.java:35) [CombatLogX.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-edd0396-20ab5d3]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-edd0396-20ab5d3]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-edd0396-20ab5d3]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-edd0396-20ab5d3]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-edd0396-20ab5d3]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-edd0396-20ab5d3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
        at com.SirBlobman.cheat.CheatPrevention.ctce(CheatPrevention.java:57) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-edd0396-20ab5d3]
        ... 12 more`

**Comment by SirBlobman** [comment]
Did you update all the expansions along with the main plugin? If you did I need to see your config
