### ISSUE TITLE
Error spam on hit

### ISSUE THREAD

**Issue by hasanas83V2001** [SirBlobman/CombatLogX#14]
When I hit a player, I get this:
https://pastebin.com/XWF5hMfn

I use the latest official release (5.2.0) and I use these expansions:
- CheatPrevention (latest version)
- CompatTowny (latest version)
- CompatWorldGuard (latest version)
- Notifier (latest version)

I have attempted re-installing the plugin but it didn't fix the error

**Comment by SirBlobman** [comment]
`Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
        at com.SirBlobman.cheat.CheatPrevention.ctce(CheatPrevention.java:57) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-65e8124-79e55b6]
        ... 47 more`

Could you please post your `combat.yml` here
