### ISSUE TITLE
[Bug Report] Unhandled exception occured in onPacketReceiving(PacketEvent) for CombatLogX

### ISSUE THREAD

**Issue by Kaisiq** [SirBlobman/CombatLogX#166]
**Describe the bug**

[07:28:51] [Netty Epoll Server IO #3/ERROR]: [CombatLogX] Unhandled exception occured in onPacketReceiving(PacketEvent) for CombatLogX
java.lang.IllegalStateException: ResidenceFlagCheckEvent may only be triggered synchronously.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595) ~[patched_1.16.3.jar:git-Paper-204]
	at com.bekvon.bukkit.residence.protection.ResidencePermissions.has(ResidencePermissions.java:216) ~[?:?]
	at com.bekvon.bukkit.residence.protection.ResidencePermissions.has(ResidencePermissions.java:205) ~[?:?]
	at com.SirBlobman.combatlogx.expansion.compatibility.residence.hook.HookResidence.isSafeZone(HookResidence.java:20) ~[?:?]
	at com.SirBlobman.combatlogx.expansion.compatibility.residence.handler.ResidenceNoEntryHandler.isSafeZone(ResidenceNoEntryHandler.java:28) ~[?:?]
	at com.SirBlobman.combatlogx.api.expansion.noentry.NoEntryForceFieldListener.isSafe(NoEntryForceFieldListener.java:23) ~[?:?]
	at com.SirBlobman.combatlogx.api.olivolja3.force.field.ForceFieldAdapter.isForceFieldBlock(ForceFieldAdapter.java:72) ~[?:?]
	at com.SirBlobman.combatlogx.api.olivolja3.force.field.ForceFieldAdapter.onPacketReceiving(ForceFieldAdapter.java:48) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:533) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-204]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:147) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.16.3.jar:git-Paper-204]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
[07:28:51] [Netty Epoll Server IO #3/ERROR]: Parameters: 
  net.minecraft.server.v1_16_R2.PacketPlayInBlockDig@33ed03e[
    a=BlockPosition{x=-836, y=114, z=125}
    b=west
    c=START_DESTROY_BLOCK
  ]

[07:28:52] [Netty Epoll Server IO #3/ERROR]: [CombatLogX] Unhandled exception occured in onPacketReceiving(PacketEvent) for CombatLogX
java.lang.IllegalStateException: ResidenceFlagCheckEvent may only be triggered synchronously.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595) ~[patched_1.16.3.jar:git-Paper-204]
	at com.bekvon.bukkit.residence.protection.ResidencePermissions.has(ResidencePermissions.java:216) ~[?:?]
	at com.bekvon.bukkit.residence.protection.ResidencePermissions.has(ResidencePermissions.java:205) ~[?:?]
	at com.SirBlobman.combatlogx.expansion.compatibility.residence.hook.HookResidence.isSafeZone(HookResidence.java:20) ~[?:?]
	at com.SirBlobman.combatlogx.expansion.compatibility.residence.handler.ResidenceNoEntryHandler.isSafeZone(ResidenceNoEntryHandler.java:28) ~[?:?]
	at com.SirBlobman.combatlogx.api.expansion.noentry.NoEntryForceFieldListener.isSafe(NoEntryForceFieldListener.java:23) ~[?:?]
	at com.SirBlobman.combatlogx.api.olivolja3.force.field.ForceFieldAdapter.isForceFieldBlock(ForceFieldAdapter.java:72) ~[?:?]
	at com.SirBlobman.combatlogx.api.olivolja3.force.field.ForceFieldAdapter.onPacketReceiving(ForceFieldAdapter.java:48) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:533) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-204]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:147) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[patched_1.16.3.jar:git-Paper-204]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.16.3.jar:git-Paper-204]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
[07:28:52] [Netty Epoll Server IO #3/ERROR]: Parameters: 
  net.minecraft.server.v1_16_R2.PacketPlayInBlockDig@37ab69b7[
    a=BlockPosition{x=-836, y=114, z=125}
    b=west
    c=STOP_DESTROY_BLOCK
  ]

**Minecraft Version**
 - git-Paper-204 (MC: 1.16.3)

**CombatLogX Version:**
 - Installed Version: v10.3.7.1

**Additional context**
Don't really know what happened before the error, but the console was spammed with the error and the players said they had lags around the time the error appeared.

**Comment by Olivoz** [comment]
Disable the unsafe option

**Comment by Kaisiq** [comment]
It is disabled, I left it as it was by default, because I do not know what it does.

**Comment by Olivoz** [comment]
Alright I think I know what the issue is. Thanks for reporting it :)

**Comment by Kaisiq** [comment]
No problem! Looking forward to the fix :)

**Comment by SirBlobman** [comment]
@Kaisiq Please inform us if the issue is still occurring with V11. You can find the beta builds on the CodeMC Jenkins server.

**Comment by SirBlobman** [comment]
No reply in 2 months, if this issue still occurrs please reopen the issue @Kaisiq
