### ISSUE TITLE
Disabled update-checker produces WARN

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#184]
**Describe the bug**
Update check is disabled in config.yml. On server start-up, a WARN message is produced for update-check.

**To Reproduce**
- Update to CLX 11.0.0.0-b392
- Set `update-checker: false` in config.yml
- Start server
- Note WARN message

**Expected behavior**
No update check should be attempted, and therefore, no WARN message produced

**CombatLogX Version:**
```
>clx version
[08:02:47] [Server thread/INFO]: 
[08:02:47] [Server thread/INFO]: Java Version: 11.0.10 (Oracle Corporation)
[08:02:47] [Server thread/INFO]: Server Version: 3029-Spigot-79d53c2-e9ad7cb (MC: 1.16.5)
[08:02:47] [Server thread/INFO]: Bukkit Version: 1.16.5-R0.1-SNAPSHOT
[08:02:47] [Server thread/INFO]: Minecraft Version: 1.16.5
[08:02:47] [Server thread/INFO]: NMS Version: 1_16_R3
[08:02:47] [Server thread/INFO]: 
[08:02:47] [Server thread/INFO]: Dependency Information:
[08:02:47] [Server thread/INFO]: - ProtocolLib v4.6.1-SNAPSHOT-b497
[08:02:47] [Server thread/INFO]: - SirBlobmanCore v2.0.4
[08:02:47] [Server thread/INFO]: - BentoBox v1.16.2-SNAPSHOT-b2040
[08:02:47] [Server thread/INFO]: - Citizens v2.0.27-SNAPSHOT (build 2279)
[08:02:47] [Server thread/INFO]: - Essentials v2.19.0-dev+99-1e0d7fb
[08:02:47] [Server thread/INFO]: - PlaceholderAPI v2.10.10-DEV-122
[08:02:47] [Server thread/INFO]: - Residence v4.9.3.3
[08:02:47] [Server thread/INFO]: - Sentinel v2.2.5-SNAPSHOT (build 406)
[08:02:47] [Server thread/INFO]: - WorldEdit v7.3.0-SNAPSHOT+5705-5b2c4fd
[08:02:47] [Server thread/INFO]: - WorldGuard v7.0.5-SNAPSHOT+2107-528ba32
[08:02:47] [Server thread/INFO]: 
[08:02:47] [Server thread/INFO]: CombatLogX by SirBlobman
[08:02:47] [Server thread/INFO]: Plugin Version: 11.0.0.0-Beta-392
[08:02:47] [Server thread/INFO]: Spigot Version: Update Checker Disabled!
[08:02:47] [Server thread/INFO]: 
[08:02:47] [Server thread/INFO]: Enabled Expansions (8):
[08:02:47] [Server thread/INFO]:  - CompatBSkyBlock
[08:02:47] [Server thread/INFO]:  - CompatCitizens
[08:02:47] [Server thread/INFO]:  - CompatEssentialsX
[08:02:47] [Server thread/INFO]:  - CompatPlaceholderAPI
[08:02:47] [Server thread/INFO]:  - CompatWorldGuard
[08:02:47] [Server thread/INFO]:  - DamageTagger
[08:02:47] [Server thread/INFO]:  - Logger
[08:02:47] [Server thread/INFO]:  - MobTagger
```

**Additional context**
SirBlobmanCore 2.0.4-b14

config.yml
```
# Should the plugin be allowed to check for updates?
# Default: true
update-checker: false
```
but on server start-up
```
[07:55:29] [Craft Scheduler Thread - 1/INFO]: [SirBlobman Core] Checking for a plugin update...
[07:55:29] [Craft Scheduler Thread - 1/INFO]: [SirBlobman Core] Checking for updates using the Spigot API...
[07:55:29] [Craft Scheduler Thread - 1/WARN]: [SirBlobman Core] An error occurred while trying to check for an update:
```

**Comment by SirBlobman** [comment]
Are you sure that's the full warning? That message should only show if there's also a stacktrace to go with it.

**Comment by SlimeDog** [comment]
The point is that the update check should not be attempted. The stack trace reflects that the attempt was blocked by NetworkInterceptor, as it is configured to do, so is not particularly useful to CLX.
```
[09:06:48] [Craft Scheduler Thread - 1/WARN]: [SirBlobman Core] An error occurred while trying to check for an update:
java.io.IOException: Connect failed
        at me.lucko.networkinterceptor.interceptors.SecurityManagerInterceptor.checkConnect(SecurityManagerInterceptor.java:31) ~[NetworkInterceptor-1.0.jar:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:552) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1071) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1069) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:795) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1068) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1512) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1510) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:795) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250) ~[?:?]
        at com.github.sirblobman.api.update.UpdateChecker.getSpigotVersion(UpdateChecker.java:92) [SirBlobmanCore-2.0.4-b14.jar:?]
        at com.github.sirblobman.api.update.UpdateChecker.run(UpdateChecker.java:36) [SirBlobmanCore-2.0.4-b14.jar:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.16.5-3029.jar:3029-Spigot-79d53c2-e9ad7cb]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.5-3029.jar:3029-Spigot-79d53c2-e9ad7cb]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by SirBlobman** [comment]
It actually seems that its SirBlobmanCore using the update checker, not CombatLogX
Make sure to disable the update checker in the config for that plugin as well.

**Comment by SlimeDog** [comment]
I should have noticed that it was identified as SirBlobmanCore, rather than CLX. Disabled in both plugins, and resolved.
