### ISSUE TITLE
Multiple problems

### ISSUE THREAD

**Issue by RainOfPain125** [SirBlobman/CombatLogX#22]
CombatLogX update checker claims there is a new ver (5.2.2.1) yet I just downloaded this off the github (ver 5.2.2.0)

Also, this error appears when I start my server and it tries to load the "cheat prevention" expansion

[23:54:10 ERROR]: Could not load 'plugins\CheatPrevention.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[patched_1.12.2.jar:git-Paper-1284]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) [patched_1.12.2.jar:git-Paper-1284]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:307) [patched_1.12.2.jar:git-Paper-1284]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [patched_1.12.2.jar:git-Paper-1284]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1284]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more
[23:54:10 ERROR]: Could not load 'plugins\CompatFactions.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[patched_1.12.2.jar:git-Paper-1284]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) [patched_1.12.2.jar:git-Paper-1284]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:307) [patched_1.12.2.jar:git-Paper-1284]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [patched_1.12.2.jar:git-Paper-1284]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1284]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more

**_EDIT:_**

Here is another error, that is being spit out when compatfactions expansion is trying to be loaded

[23:57:53 ERROR]: Could not load 'plugins\CompatFactions.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[patched_1.12.2.jar:git-Paper-1284]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136) [patched_1.12.2.jar:git-Paper-1284]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:307) [patched_1.12.2.jar:git-Paper-1284]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [patched_1.12.2.jar:git-Paper-1284]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1284]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more

**Comment by SirBlobman** [comment]
Spigot has the latest versions,  not GitHub (I forget to update GitHub)
Also,  expansions go into the expansions folder  of CombatLogX, not plugins

**Comment by RainOfPain125** [comment]
thanks. sorry for my stupidity

**Comment by SirBlobman** [comment]
No problem
