### ISSUE TITLE
java.util.ConcurrentModificationException: null error sometimes

### ISSUE THREAD

**Issue by andris155** [SirBlobman/CombatLogX#222]
**Describe the bug**
java.util.ConcurrentModificationException: null error sometimes

**To Reproduce**
CombatlogX writes this error sometimes. I don't know what is caused.

**Expected behavior**
No java.util.ConcurrentModificationException: null errors.

[14:51:15 INFO]: Java Version: 16.0.1 (Oracle Corporation)
[14:51:15 INFO]: Server Version: git-Paper-96 (MC: 1.17.1)
[14:51:15 INFO]: Bukkit Version: 1.17.1-R0.1-SNAPSHOT
[14:51:15 INFO]: Minecraft Version: 1.17.1
[14:51:15 INFO]: NMS Version: 1_17_R1
[14:51:15 INFO]: 
[14:51:15 INFO]: Dependency Information:
[14:51:15 INFO]: - SirBlobmanCore v2.2.4
[14:51:15 INFO]: - Citizens v2.0.28-SNAPSHOT (build 2348)
[14:51:15 INFO]: - Essentials v2.19.0-dev+218-cca98e8
[14:51:15 INFO]: - GriefPrevention v16.17.1-2b69191
[14:51:15 INFO]: - PlaceholderAPI v2.10.10
[14:51:15 INFO]: - ProtocolLib v4.7.1-SNAPSHOT-b530
[14:51:15 INFO]: - FastAsyncWorldEdit v1.17-49;41073bb
[14:51:15 INFO]: - WorldGuard v7.0.6-beta1+0b66f3e
[14:51:15 INFO]: 
[14:51:15 INFO]: CombatLogX by SirBlobman
[14:51:15 INFO]: Plugin Version: 11.0.0.0-Beta-534
[14:51:15 INFO]: Spigot Version: Update Checker Disabled!
[14:51:15 INFO]: 
[14:51:15 INFO]: Enabled Expansions (1):
[14:51:15 INFO]:  - CheatPrevention

**Additional context**
```
[20:06:34] [Craft Scheduler Thread - 1430/WARN]: [CombatLogX] Plugin CombatLogX v11.0.0.0-Beta-534 generated an exception while executing task 105
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1584) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1607) ~[?:?]
	at java.util.AbstractCollection.addAll(AbstractCollection.java:335) ~[?:?]
	at java.util.HashSet.<init>(HashSet.java:121) ~[?:?]
	at com.github.sirblobman.combatlogx.manager.CombatManager.getPlayersInCombat(CombatManager.java:133) ~[?:?]
	at com.github.sirblobman.combatlogx.task.TimerUpdateTask.run(TimerUpdateTask.java:45) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-90]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-90]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-90]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Olivoz** [comment]
Thanks for reporting the issue. We'll look in to the issue :)
