### ISSUE TITLE
nms not detect api server 1.17.1

### ISSUE THREAD

**Issue by dinobossytnew** [SirBlobman/CombatLogX#304]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

[21:10:48 ERROR]: Could not pass event PlayerCombatTimerChangeEvent to CombatLogX v10.4.2.4
java.lang.NoSuchMethodError: 'com.github.sirblobman.api.nms.bossbar.BossBarHandler com.github.sirblobman.api.nms.MultiVersionHandler.getBossBarHandler()'
        at com.SirBlobman.combatlogx.expansion.notifier.manager.BossBarManager.updateBossBar(BossBarManager.java:59) ~[?:?]
        at com.SirBlobman.combatlogx.expansion.notifier.listener.ListenerNotifier.onTimerChange(ListenerNotifier.java:41) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor750.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1415]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1415]
        at com.SirBlobman.combatlogx.manager.CombatManager.lambda$run$0(CombatManager.java:217) ~[CombatLogX.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Purpur-1415]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Purpur-1415]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[21:10:48 WARN]: [CombatLogX] Task #1495423 for CombatLogX v10.4.2.4 generated an exception
java.lang.NoSuchMethodError: 'com.github.sirblobman.api.nms.bossbar.BossBarHandler com.github.sirblobman.api.nms.MultiVersionHandler.getBossBarHandler()'
        at com.SirBlobman.combatlogx.expansion.notifier.manager.BossBarManager.removeBossBar(BossBarManager.java:71) ~[?:?]
        at com.SirBlobman.combatlogx.expansion.notifier.listener.ListenerNotifier.lambda$onUntag$2(ListenerNotifier.java:110) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1415]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1415]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1588) ~[patched_1.17.1.jar:git-Purpur-1415]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1415]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1504) ~[patched_1.17.1.jar:git-Purpur-1415]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1297) ~[patched_1.17.1.jar:git-Purpur-1415]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1415]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

### Reproduction Steps

WHEN I GET CAUGHT IN PVP THE USERS START TO NAB.

### Expected behaviour

api plugin not detect version 1.17.1 paper purpure

### Screenshots / Videos

not

### latest log file (if applicable)

if this happens, the pc explodes. 40 users

### CombatLogX Version

last

### Anything else?

in the onyx server they use your plugin bro and they are assholes to see errors here toy yo el papu de tu corazon if you solve me or tell us something or solution.

**Comment by Olivoz** [comment]
This is Purpur not Paper. Also please provide the output from "/clx version" instead of "last". As for the actual issue update SirBlobmanCore.

**Comment by SirBlobman** [comment]
@dinobossytnew 
Like Olivo said, it looks like SirBlobmanCore is out-of-date. If the issue still occurrs after updating, please reopen the issue.
