### ISSUE TITLE
Could not pass event PlayerUntagEvent to CombatLogX

### ISSUE THREAD

**Issue by mibby** [SirBlobman/CombatLogX#31]
Citizens dev 1506
CombatLogX as of commit https://github.com/SirBlobman/CombatLogX/commit/34e0b977ba07524ebe80a4f30fe5f722c11be82b
With the Citizens expansion.

```
[16:10:49] [Server thread/ERROR]: Could not pass event PlayerUntagEvent to CombatLogX v6.0.0.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1337]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1337]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1337]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1337]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1337]
	at com.SirBlobman.combatlogx.utility.Util.call(Util.java:174) [CombatLogX.jar:?]
	at com.SirBlobman.combatlogx.listener.ListenBukkit.quit(ListenBukkit.java:132) [CombatLogX.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor585.execute(Unknown Source) [?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) [patched_1.12.2.jar:git-Paper-1337]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) [patched_1.12.2.jar:git-Paper-1337]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [patched_1.12.2.jar:git-Paper-1337]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) [patched_1.12.2.jar:git-Paper-1337]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) [patched_1.12.2.jar:git-Paper-1337]
	at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:429) [patched_1.12.2.jar:git-Paper-1337]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1147) [patched_1.12.2.jar:git-Paper-1337]
	at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:342) [patched_1.12.2.jar:git-Paper-1337]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:184) [patched_1.12.2.jar:git-Paper-1337]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:941) [patched_1.12.2.jar:git-Paper-1337]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1337]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1337]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1337]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.NullPointerException
	at net.citizensnpcs.api.trait.trait.Inventory.setContents(Inventory.java:160) ~[citizens-2.0.22-SNAPSHOT.jar:?]
	at com.SirBlobman.citizens.utility.NPCUtil.createNPC(NPCUtil.java:42) ~[CompatCitizens.jar:?]
	at com.SirBlobman.citizens.ListenCitizens.pue(ListenCitizens.java:29) ~[CompatCitizens.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor593.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1337]
	... 21 more
```

**Comment by SirBlobman** [comment]
This is an unreleased beta version, but thanks for reporting the bug :)

**Comment by SirBlobman** [comment]
Should be fixed now
