### ISSUE TITLE
Elytras 

### ISSUE THREAD

**Issue by IceWaffles** [SirBlobman/CombatLogX#328]
### Server Implementation

Paper

### Server Version

1.17.1

### CombatLogX Version

18:48:55 WARN]: Unexpected exception while parsing console command "clx version"
org.bukkit.command.CommandException: Unhandled exception executing command 'clx' in plugin CombatLogX v11.0.0.0-Beta-657
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Pufferfish-4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Pufferfish-4]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Pufferfish-4]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:832) ~[patched_1.17.1.jar:git-Pufferfish-4]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:545) ~[patched_1.17.1.jar:git-Pufferfish-4]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:507) ~[patched_1.17.1.jar:git-Pufferfish-4]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1500) ~[patched_1.17.1.jar:git-Pufferfish-4]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1293) ~[patched_1.17.1.jar:git-Pufferfish-4]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:323) ~[patched_1.17.1.jar:git-Pufferfish-4]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'boolean com.github.sirblobman.combatlogx.command.CommandCombatLogX.checkPermission(org.bukkit.command.CommandSender, java.lang.String, boolean)'
        at com.github.sirblobman.combatlogx.command.CommandCombatLogX.commandVersion(CommandCombatLogX.java:231) ~[CombatLogX.jar:?]
        at com.github.sirblobman.combatlogx.command.CommandCombatLogX.execute(CommandCombatLogX.java:110) ~[CombatLogX.jar:?]
        at com.github.sirblobman.api.command.Command.onCommand(Command.java:437) ~[SirBlobmanCore-2.3.1-Dev.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Pufferfish-4]

### Feature Request

Ignore the CLX version output, the plugin runs fine. The main request is this: Is it possible to disable elytras from being opened in combat but not allow them to be disabled once used? For example, so if player A and B are in combat, then neither can use their elytra. However, if A is flying, and B shoots them, make it so they don't fall out of the sky? The main concern is that Elytra tagging someone over the void or lava sea would be an instant death. Maybe have a way to disable it (this one elytra thing)  for the end and nether? Preferably though have them not fall out of the sky during elytra use; that would be the preferred and best solution.

**Comment by SirBlobman** [comment]
Please update SirBlobmanCore to fix the command errors @IceWaffles
