### ISSUE TITLE
Spam console Could not pass event PlayerCombatTimerChangeEvent to CombatLogX v10.4.2.4

### ISSUE THREAD

**Issue by WolverStones** [SirBlobman/CombatLogX#332]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

The console is spamming an error. 

### Reproduction Steps

I didn't figure out how the problem came about 

### Expected behaviour

...

### latest log file (if applicable)

https://pastebin.com/

### CombatLogX Version

10.4.2.4

**Comment by Olivoz** [comment]
Could you send the error in a paste?

**Comment by WolverStones** [comment]
> 
```
[23:55:21 ERROR]: Could not pass event PlayerCombatTimerChangeEvent to CombatLogX v10.4.2.4
java.lang.NoSuchMethodError: 'com.SirBlobman.combatlogx.api.shaded.nms.MultiVersionHandler com.SirBlobman.combatlogx.api.ICombatLogX.getMultiVersionHandler()'
at com.SirBlobman.combatlogx.expansion.notifier.manager.BossBarManager.updateBossBar(BossBarManager.java:58) ~[?:?]
at com.SirBlobman.combatlogx.expansion.notifier.listener.ListenerNotifier.onTimerChange(ListenerNotifier.java:35) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor962.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-398]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Paper-398]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-398]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-398]
at com.SirBlobman.combatlogx.manager.CombatManager.lambda$run$0(CombatManager.java:217) ~[CombatLogX.jar:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-398]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-398]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-398]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:831) ~[?:?] 
```

**Comment by WolverStones** [comment]
```
WolverStone issued server command: /pvptoggle
>.... [00:08:11 ERROR]: Could not pass event PlayerCommandPreprocessEvent to CombatLogX v10.4.2.4
java.lang.NoSuchMethodError: 'com.SirBlobman.combatlogx.api.utility.ILanguageManager com.SirBlobman.combatlogx.api.ICombatLogX.getLanguageManager()'
at com.SirBlobman.combatlogx.expansion.newbie.helper.command.CommandTogglePVP.togglePVP(CommandTogglePVP.java:95) ~[?:?]
at com.SirBlobman.combatlogx.expansion.newbie.helper.command.CommandTogglePVP.onCommand(CommandTogglePVP.java:26) ~[?:?]
at com.SirBlobman.combatlogx.command.CustomCommand.execute(CustomCommand.java:24) ~[CombatLogX.jar:?]
at com.SirBlobman.combatlogx.command.CustomCommand.beforeCommand(CustomCommand.java:41) ~[CombatLogX.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor959.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-398]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-398]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-398]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-398]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2254) ~[app:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-398]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-398]
at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-398]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-398]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-398]
at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[app:?]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1536) ~[patched_1.17.1.jar:git-Paper-398]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-398]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-398]
at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by SirBlobman** [comment]
@WolverStones Please send the output of the command `/about SirBlobmanCore`

**Comment by WolverStones** [comment]
> /about SirBlobmanCore

[00:41:34 INFO]: SirBlobmanCore version 2.3.4
[00:41:34 INFO]: A core plugin with a lot of useful classes for other projects.
[00:41:34 INFO]: Author: SirBlobman

**Comment by SirBlobman** [comment]
> > /about SirBlobmanCore
> 
> [00:41:34 INFO]: SirBlobmanCore version 2.3.4 [00:41:34 INFO]: A core plugin with a lot of useful classes for other projects. [00:41:34 INFO]: Author: SirBlobman

Thanks. It seems SirBlobmanCore is already up-to-date. Please try re-downloading the latest CombatLogX.zip file and make sure to update your expansions when updating the main jar.

**Comment by WolverStones** [comment]
> > > /about SirBlobmanCore
> > 
> > 
> > [00:41:34 INFO]: SirBlobmanCore version 2.3.4 [00:41:34 INFO]: A core plugin with a lot of useful classes for other projects. [00:41:34 INFO]: Author: SirBlobman
> 
> Thanks. It seems SirBlobmanCore is already up-to-date. Please try re-downloading the latest CombatLogX.zip file and make sure to update your expansions when updating the main jar.

Thanks for your help. Working fine now.
