### ISSUE TITLE
java.lang.NoSuchFieldException: modifiers

### ISSUE THREAD

**Issue by Minecon724** [SirBlobman/CombatLogX#348]
### Server Implementation

Paper

### Server Version

1.8.8

### Describe the bug

bossbar is not working and spams with this error:
```
[18:07:53 WARN]: java.lang.NoSuchFieldException: modifiers

[18:07:53 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)

[18:07:53 WARN]:        at com.github.sirblobman.bossbar.legacy.reflection.AccessUtil.setAccessible(AccessUtil.java:10)

[18:07:53 WARN]:        at com.github.sirblobman.bossbar.legacy.reflection.ClassBuilder.buildWitherSpawnPacket(ClassBuilder.java:16)

[18:07:53 WARN]:        at com.github.sirblobman.bossbar.legacy.BossBar.spawn(BossBar.java:157)

[18:07:53 WARN]:        at com.github.sirblobman.bossbar.legacy.BossBar.setVisible(BossBar.java:93)

[18:07:53 WARN]:        at com.github.sirblobman.bossbar.legacy.BossBarAPI.setMessage(BossBarAPI.java:52)

[18:07:53 WARN]:        at com.github.sirblobman.bossbar.legacy.BossBarAPI.setMessage(BossBarAPI.java:31)

[18:07:53 WARN]:        at com.github.sirblobman.bossbar.legacy.BossBarAPI.setMessage(BossBarAPI.java:27)

[18:07:53 WARN]:        at com.github.sirblobman.bossbar.legacy.BossBarWrapper_Legacy.setTitle(BossBarWrapper_Legacy.java:47)

[18:07:53 WARN]:        at com.github.sirblobman.bossbar.BossBarHandler.updateBossBar(BossBarHandler.java:57)

[18:07:53 WARN]:        at com.SirBlobman.combatlogx.expansion.notifier.manager.BossBarManager.removeBossBar(BossBarManager.java:86)

[18:07:53 WARN]:        at com.SirBlobman.combatlogx.expansion.notifier.listener.ListenerNotifier.lambda$onUntag$2(ListenerNotifier.java:110)

[18:07:53 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)

[18:07:53 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)

[18:07:53 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:793)

[18:07:53 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:398)

[18:07:53 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:723)

[18:07:53 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)

[18:07:53 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Reproduction Steps

it happens in combat with notifier expansion installed

### Expected behaviour

no errors?

### CombatLogX Version
```
[18:12:34 INFO]: Getting version information for CombatLogX...

[18:12:34 INFO]: 

[18:12:34 INFO]: Server Version: git-NachoSpigot-"2cefae4" (MC: 1.8.8)

[18:12:34 INFO]: Bukkit Version: 1.8.8-R0.2-SNAPSHOT

[18:12:34 INFO]: Minecraft Version: 1.8.8

[18:12:34 INFO]: NMS Version: 1_8_R3

[18:12:34 INFO]: 

[18:12:34 INFO]: CombatLogX by SirBlobman

[18:12:34 INFO]: Installed Version: v10.4.2.4

[18:12:34 INFO]: Latest Version: v10.4.2.4

[18:12:34 INFO]: 

[18:12:34 INFO]: Getting expansion versions...

[18:12:34 INFO]: 

[18:12:34 INFO]:   PlaceholderAPI Compatibility v15.1

[18:12:34 INFO]:   Notifier v15.13
```
using java 17 if it matters

**Comment by Olivoz** [comment]
The reflection that is used for the bossbar in 1.8 does not work with Java 17. Downgrade Java, Update to a modern version or disable the bossbar in the bossbar.yml. The bossbar.yml is located in /plugins/CombatLogX/expansions/Notifier/

**Comment by Minecon724** [comment]
:/
