### ISSUE TITLE
Issues with TemporaryPlayer coming from ProtocolLib updates.

### ISSUE THREAD

**Issue by RealTriassic** [SirBlobman/CombatLogX#383]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

ProtocolLib has pushed changes to their plugin that break compatibility with CombatLogX.

### The error
```
[04:27:44 ERROR]: [CombatLogX] Unhandled exception number 4096 occured in onPacketSending(PacketEvent) for CombatLogX
java.lang.NoClassDefFoundError: com/comphenix/protocol/injector/server/TemporaryPlayer
        at com.SirBlobman.combatlogx.api.olivolja3.force.field.ForceFieldAdapter.onPacketSending(ForceFieldAdapter.java:80) ~[CombatLogX-10.4.2.4.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib-#551.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib-#551.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:558) ~[ProtocolLib-#551.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:532) ~[ProtocolLib-#551.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:95) ~[ProtocolLib-#551.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:517) ~[ProtocolLib-#551.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.access$000(NettyChannelInjector.java:40) ~[ProtocolLib-#551.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:450) ~[ProtocolLib-#551.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib-#551.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:435) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:382) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2113) ~[?:?]
        at xuan.cat.fartherviewdistance.code.branch.v18.Branch_18_ProxyPlayerConnection.a(Branch_18_ProxyPlayerConnection.java:109) ~[FartherViewDistance-9.1.2.jar:?]
        at xuan.cat.fartherviewdistance.code.branch.v18.Branch_18_ProxyPlayerConnection.a(Branch_18_ProxyPlayerConnection.java:85) ~[FartherViewDistance-9.1.2.jar:?]
        at net.minecraft.server.level.ChunkHolder.broadcast(ChunkHolder.java:416) ~[?:?]
        at net.minecraft.server.level.ChunkHolder.broadcastChanges(ChunkHolder.java:356) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:1075) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:918) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:649) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1619) ~[paper-1.18.2.jar:git-Paper-249]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[paper-1.18.2.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[paper-1.18.2.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[paper-1.18.2.jar:git-Paper-249]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[paper-1.18.2.jar:git-Paper-249]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.injector.server.TemporaryPlayer
        ... 26 more
```

### Reproduction Steps

1. Download the latest ProtocolLib build from [here](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/).
2. Run CombatLogX with the latest ProtocolLib dev build.
3. Join the server
4. Observe the error

### Expected behaviour

No errors should occur

### CombatLogX Version

```
[04:26:13 INFO]: Getting version information for CombatLogX...
[04:26:13 INFO]: 
[04:26:13 INFO]: Server Version: git-Paper-249 (MC: 1.18.2)
[04:26:13 INFO]: Bukkit Version: 1.18.2-R0.1-SNAPSHOT
[04:26:13 INFO]: Minecraft Version: 1.18.2
[04:26:13 INFO]: NMS Version: 1_18_R2
[04:26:13 INFO]: 
[04:26:13 INFO]: CombatLogX by SirBlobman
[04:26:13 INFO]: Installed Version: v10.4.2.4
[04:26:13 INFO]: Latest Version: vUpdate Checker Disabled!
[04:26:13 INFO]: 
[04:26:13 INFO]: Getting expansion versions...
[04:26:13 INFO]: 
[04:26:13 INFO]:   Cheat Prevention v15.3
[04:26:13 INFO]:   WorldGuard Compatibility v15.3
[04:26:13 INFO]:   Notifier v15.13
```

### Anything else?

The developer says that TemporaryPlayer wasn't meant to be used, they said this in a comment at [this github issue report](https://github.com/dmulloy2/ProtocolLib/issues/1538)

### Image
<img width="661" alt="image" src="https://user-images.githubusercontent.com/40073455/158163417-eae43dda-59eb-4ac5-b82a-6b98849e6d57.png">

**Comment by celticpixie** [comment]
I'm having this exact same issue - any chance your server is kicking players? No tps issues or lag?

**Comment by Olivoz** [comment]
Thank you for reporting the issue.

As a temporary fix use the v11 beta builds available on our jenkins page and do NOT install the ForceField expansion:
https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX/

Keep in mind that when migrating for v10 to v11 you will need to remove all old configs and expansions.
