### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#43]
Spigot 1.12.2 latest
CombatLogX 7.0.0.0
I updated the config, but perhaps I missed something.

plugins/CombatLogX/expansions contains:
```
CompatCitizens/
CompatCitizens-7.0.0.0.jar
CompatFactions/
CompatFactions-7.0.0.0.jar
CompatPlaceholderAPI-7.0.0.0.jar
CompatWorldGuard/
CompatWorldGuard-7.0.0.0.jar
NotCombatLogX/
NotCombatLogX-7.0.0.0.ja
```
As you can see, I removed the expansions that I don't need. On start-up, the following error is generated:
```
[21:33:15] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/SirBlobman/preciousstones/config/ConfigPreciousStones
[21:33:15] [Server thread/WARN]: 	at com.SirBlobman.factions.CompatFactions.enable(CompatFactions.java:36)
[21:33:15] [Server thread/WARN]: 	at com.SirBlobman.combatlogx.expansion.Expansions.loadExpansion(Expansions.java:39)
[21:33:15] [Server thread/WARN]: 	at com.SirBlobman.combatlogx.expansion.Expansions.loadExpansions(Expansions.java:84)
[21:33:15] [Server thread/WARN]: 	at com.SirBlobman.combatlogx.CombatLogX$1.run(CombatLogX.java:41)
[21:33:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[21:33:15] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[21:33:15] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[21:33:15] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[21:33:15] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[21:33:15] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[21:33:15] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[21:33:15] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.SirBlobman.preciousstones.config.ConfigPreciousStones
[21:33:15] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[21:33:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152)
[21:33:15] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[21:33:15] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[21:33:15] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[21:33:15] [Server thread/WARN]: 	... 11 more
```
It is not clear to me why CompatFactions requires ConfigPreciousStones, or where that is defined. Note that adding
> CompatPreciousStones-7.0.0.0.jar

to plugins/CombatLogX/expansions and restarting did not resolve the issue.

**Comment by SirBlobman** [comment]
I made a mistake, fixed it in 7.0.0.1, sorry about that
