### ISSUE TITLE
IncompatibleClassChangeError on start-up

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#503]
### Server Implementation

Spigot

### Server Version

1.19.1

### Describe the bug

Server version: Spigot 1.19.2

Error on server start-up

```
[05:45:37] [Server thread/INFO]: [CombatLogX] Enabling CombatLogX v11.1.0.4.Beta-965
[05:45:37] [Server thread/INFO]: CombatLogX was loaded successfully.^[[m
[05:45:37] [Server thread/ERROR]: Error occurred while enabling CombatLogX v11.1.0.4.Beta-965 (Is it up to date?)
java.lang.IncompatibleClassChangeError: class com.github.sirblobman.combatlogx.api.command.CombatLogCommand overrides final method com.github.sirblobman.api.command.Command.sendMessageWithPrefix(Lorg/bukkit/command/CommandSender;Ljava/lang/String;Lcom/github/sirblobman/api/language/Replacer;)V
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:193) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:193) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at com.github.sirblobman.combatlogx.CombatPlugin.registerCommands(CombatPlugin.java:261) ~[CombatLogX-11.1.0.4-b965.jar:?]
        at com.github.sirblobman.combatlogx.CombatPlugin.onEnable(CombatPlugin.java:96) ~[CombatLogX-11.1.0.4-b965.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:525) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:439) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:584) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:403) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:968) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3580-Spigot-e53686f-5901d58]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Reproduction Steps

- Update to BlueSlimeCore 2.5.5.Dev-211
- Update to CLX 11.1.0.4.Beta-965
- Start server

### Expected behaviour

No errors on start-up

### CombatLogX Version

`clx version` fails to run

BlueSlimeCore 2.5.5.Dev-211
CLX 11.1.0.4.Beta-965

**Comment by Olivoz** [comment]
Make sure to use the SirBlobmanCore version from the CombatLogX zip

**Comment by SlimeDog** [comment]
Yeah, BlueSlimeCore b211 broke it. (I think updates to BlueSlimeCore shouldn't do that, but ok.)

**Comment by SlimeDog** [comment]
Please add version and build numbers to the BlueSlimeCore jar in the CombatLogX zip file.
