### ISSUE TITLE
WorldGuard hook error

### ISSUE THREAD

**Issue by andris155** [SirBlobman/CombatLogX#51]
```
[17:27:53] [Server thread/ERROR]: Could not pass event PlayerCombatEvent to CombatLogX v8.0.0.0
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(Lorg/bukkit/World;)Lcom/sk89q/worldguard/protection/managers/RegionManager;
	at com.SirBlobman.worldguard.WorldGuardUtil.getRegions(WorldGuardUtil.java:35) ~[?:?]
	at com.SirBlobman.worldguard.WorldGuardUtil.isSafeZone(WorldGuardUtil.java:41) ~[?:?]
	at com.SirBlobman.worldguard.CompatWorldGuard.pce(CompatWorldGuard.java:57) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1038.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at com.SirBlobman.combatlogx.utility.Util.call(Util.java:221) ~[?:?]
	at com.SirBlobman.combatlogx.listener.ListenBukkit.eve(ListenBukkit.java:67) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1021.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:98) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:659) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:558) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:691) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity0(EntityLiving.java:1516) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity0(EntityHuman.java:911) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:989) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity(EntityHuman.java:824) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at net.minecraft.server.v1_13_R2.EntityPlayer.damageEntity(EntityPlayer.java:654) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at net.minecraft.server.v1_13_R2.EntityHuman.attack(EntityHuman.java:1086) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at net.minecraft.server.v1_13_R2.EntityPlayer.attack(EntityPlayer.java:1398) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2004) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:428) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.1.jar:git-Paper-"a3677899"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by andris155** [comment]
Paper 1.13.1
https://ci.athion.net/job/FAWE-WorldGuard-1.13/

**Comment by SirBlobman** [comment]
Use the beta links provided on spigot, 8.0.0.0 does not support 1.13+ yet
