### ISSUE TITLE
SavageFactions compatibility

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#53]
Spigot 1.13.1 latest
CLX 9.0.0.0-b8
SavageFactions 1.6.9.5-U0.2.1-RC-1.4-RC-2

On start-up:
```
[06:59:00] [Server thread/WARN]: java.lang.NoSuchMethodError: com.SirBlobman.combatlogx.utility.Util.regEvents([Lorg/bukkit/event/Listener;)V
[06:59:00] [Server thread/WARN]:        at com.SirBlobman.factions.CompatFactions.enable(CompatFactions.java:38)
[06:59:00] [Server thread/WARN]:        at com.SirBlobman.combatlogx.expansion.Expansions.loadExpansion(Expansions.java:48)
[06:59:00] [Server thread/WARN]:        at com.SirBlobman.combatlogx.expansion.Expansions.loadExpansions(Expansions.java:115)
[06:59:00] [Server thread/WARN]:        at com.SirBlobman.combatlogx.CombatLogX.lambda$onEnable$0(CombatLogX.java:50)
[06:59:00] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76)
[06:59:00] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[06:59:00] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893)
[06:59:00] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[06:59:00] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[06:59:00] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[06:59:00] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by SirBlobman** [comment]
CompatFactions has not been made for the beta het

**Comment by SirBlobman** [comment]
SavageFactions compatibilitys should work in Beta 9

**Comment by SlimeDog** [comment]
Thanks. I hope it is of value to someone. I am using WorldGuard for the features I used to derive from (the apparently abandoned) Factions. I uninstalled SavageFactions, based on support attitude in the forum. :(

**Comment by SirBlobman** [comment]
Thanks for all your help ☺
