### ISSUE TITLE
WorldGuard PlayerMoveEvent error

### ISSUE THREAD

**Issue by RikoDEV** [SirBlobman/CombatLogX#54]
CombatLogX: `v8.0.0.3`
WorldGuard: `7.0.0-SNAPSHOT;1753-0dc5781`
`This server is running Paper version git-Paper-366 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)`

```
[Server thread/ERROR]: Could not pass event PlayerMoveEvent to CombatLogX v8.0.0.3
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(Lorg/bukkit/World;)Lcom/sk89q/worldguard/protection/managers/RegionManager;
	at com.SirBlobman.worldguard.WorldGuardUtil.getRegions(WorldGuardUtil.java:35) ~[?:?]
	at com.SirBlobman.worldguard.WorldGuardUtil.isSafeZone(WorldGuardUtil.java:41) ~[?:?]
	at com.SirBlobman.worldguard.olivolja3.ForceField.getChangedBlocks(ForceField.java:101) ~[?:?]
	at com.SirBlobman.worldguard.olivolja3.ForceField.updateViewedBlocks(ForceField.java:50) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor789.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.1.jar:git-Paper-366]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.1.jar:git-Paper-366]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.1.jar:git-Paper-366]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.1.jar:git-Paper-366]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1009) ~[patched_1.13.1.jar:git-Paper-366]
	at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.13.1.jar:git-Paper-366]
	at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.13.1.jar:git-Paper-366]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.1.jar:git-Paper-366]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.1.jar:git-Paper-366]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.1.jar:git-Paper-366]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[patched_1.13.1.jar:git-Paper-366]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.1.jar:git-Paper-366]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.1.jar:git-Paper-366]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```

**Comment by SirBlobman** [comment]
8.0.0.3 is not for 1.13
Use the beta
