### ISSUE TITLE
Need WorldEdit/WorldGuard vector update

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#56]
Spigot 1.13.2 latest
CombatLogX 9.0.0.0-b22
worldguard-legacy 7.0.0-b1754
worldedit-bukkit 7.0.0-b3933

WorldEdit introduced Vectors. I'm guessing CombatLogX needs to recompile with the new API.
```
[08:57:44] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to CombatLogX v9.0.0.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.2.jar-2018-11-03-0808:git-Spigot-2474d93-f0398e4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar-2018-11-03-0808:git-Spigot-2474d93-f0398e4]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar-2018-11-03-0808:git-Spigot-2474d93-f0398e4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar-2018-11-03-0808:git-Spigot-2474d93-f0398e4]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:948) ~[spigot-1.13.2.jar-2018-11-03-0808:git-Spigot-2474d93-f0398e4]
        at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[spigot-1.13.2.jar-2018-11-03-0808:git-Spigot-2474d93-f0398e4]
        at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[spigot-1.13.2.jar-2018-11-03-0808:git-Spigot-2474d93-f0398e4]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar-2018-11-03-0808:git-Spigot-2474d93-f0398e4]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar-2018-11-03-0808:git-Spigot-2474d93-f0398e4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar-2018-11-03-0808:git-Spigot-2474d93-f0398e4]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar-2018-11-03-0808:git-Spigot-2474d93-f0398e4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar-2018-11-03-0808:git-Spigot-2474d93-f0398e4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar-2018-11-03-0808:git-Spigot-2474d93-f0398e4]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.util.Location.toVector()Lcom/sk89q/worldedit/Vector;
        at com.SirBlobman.expansion.compatworldguard.utility.WGUtil.getLocation(WGUtil.java:84) ~[?:?]
        at com.SirBlobman.expansion.compatworldguard.utility.WGUtil.getRegions(WGUtil.java:95) ~[?:?]
        at com.SirBlobman.expansion.compatworldguard.utility.WGUtil.allowsPvP(WGUtil.java:100) ~[?:?]
        at com.SirBlobman.expansion.compatworldguard.olivolja3.ForceField.isSafeZone(ForceField.java:56) ~[?:?]
        at com.SirBlobman.expansion.compatworldguard.olivolja3.ForceField.updateViewedBlocks(ForceField.java:66) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor240.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.2.jar-2018-11-03-0808:git-Spigot-2474d93-f0398e4]
        ... 15 more
```

**Comment by SirBlobman** [comment]
At this time I can only support the WorldGuard/WorldEdit that is released on BukkitDev

Once the version with vectors is public I will update CombatLogX

**Comment by SlimeDog** [comment]
Understood.

**Comment by SlimeDog** [comment]
There is a 7.0.0 (vector) version of WG/WE on BukkitDev.

**Comment by SirBlobman** [comment]
WorldGuard Compatibility 7 should work. If not, you can re-open this issue
