### ISSUE TITLE
CompatLands is Broken with latest Lands version

### ISSUE THREAD

**Issue by Dagrond** [SirBlobman/CombatLogX#566]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

Recently Lands changed some of their APIs, and it seems that compatLands is not working with these changes. (For more information look into update log of Lands in spigot).
This is error that I get trying to run Lands 6.26.2 with CLX 11.1.0.7.1025 and CompatLands expansion on purpur 1.19.3:
`[15:47:48] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to CombatLogX v11.1.0.7.1025
java.lang.NoSuchFieldError: ATTACK_PLAYER
	at combatlogx.expansion.compatibility.region.lands.LandsRegionHandler.isSafeZone(LandsRegionHandler.java:40) ~[?:?]
	at com.github.sirblobman.combatlogx.api.expansion.region.RegionMoveListener.onMove(RegionMoveListener.java:40) ~[CombatLogX.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor994.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1873]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1665) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1873]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### Reproduction Steps

1. Download lastest version of Lands, CombatLogX and CompatLands expansion
2. start server
3. start a pvp
4. look in console for errors

### Expected behaviour

Welp, no errors in console

### CombatLogX Version

[15:52:16 INFO]: Java Version: 17.0.5
[15:52:16 INFO]: Java Vendor: Private Build
[15:52:16 INFO]:
[15:52:16 INFO]: Server Version: git-Purpur-1873 (MC: 1.19.3)
[15:52:16 INFO]: Bukkit Version: 1.19.3-R0.1-SNAPSHOT
[15:52:16 INFO]: Minecraft Version: 1.19.3
[15:52:16 INFO]: NMS Version: 1_19_R2
[15:52:16 INFO]:
[15:52:16 INFO]: Dependency Information:
[15:52:16 INFO]:  - BlueSlimeCore v2.6.0.18
[15:52:16 INFO]:  - Citizens v2.0.30-SNAPSHOT (build 2846)
[15:52:16 INFO]:  - CMI v9.3.0.2
[15:52:16 INFO]:  - Lands v6.26.2
[15:52:16 INFO]:  - PlaceholderAPI v2.11.2
[15:52:16 INFO]:  - ProtocolLib v5.0.0-SNAPSHOT-b600
[15:52:16 INFO]:  - WorldGuard v7.0.7+216b061
[15:52:16 INFO]:  - ViaVersion v4.5.1
[15:52:16 INFO]:
[15:52:16 INFO]: CombatLogX by SirBlobman
[15:52:16 INFO]: Plugin Version: 11.1.0.7.1025
[15:52:16 INFO]: Spigot Version: 11.1.0.7.1025
[15:52:16 INFO]:
[15:52:16 INFO]: Enabled Expansions (4):
[15:52:16 INFO]:  - BossBar
[15:52:16 INFO]:  - CompatCMI
[15:52:16 INFO]:  - CompatLands
[15:52:16 INFO]:  - CompatPlaceholderAPI

**Comment by SirBlobman** [comment]
My auto-build script for Lands API broke, they switched from Maven to Gradle. I will fix it soon.

**Comment by SirBlobman** [comment]
Fixed in commit f3391d916aa439d29afbc3563d344ba8b65cf297
