### ISSUE TITLE
EventException when I killed a spider

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#58]
Spigot 1.13.2 latest
ExtraHardMode 3.13.0-3.3.2-411
CLX 9.0.1.1
CLX/expansions/CompatCitizens-9.0.1.1
CLX/expansions/CompatPlaceholderAPI-9.0.1.1
CLX/expansions/CompatWorldGuard-7.0-9.0.1.1
CLX/expansions/NotCombatLogX-9.0.1.1

```
[22:19:34 ERROR]: Could not pass event EntityDeathEvent to MobHunting v6.0.8
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:474) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.EntityLiving.die(EntityLiving.java:1205) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1055) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.EntityMonster.damageEntity(SourceFile:61) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.EntityArrow.b(EntityArrow.java:331) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.EntityArrow.a(EntityArrow.java:274) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.EntityArrow.tick(EntityArrow.java:199) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.EntityTippedArrow.tick(EntityTippedArrow.java:86) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1380) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.World.g(World.java:1347) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1181) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:601) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:972) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.util.Location.toVector()Lcom/sk89q/worldedit/Vector;
        at one.lindegaard.MobHunting.compatibility.WorldGuardHelper.isAllowedByWorldGuard(WorldGuardHelper.java:96) ~[?:?]
        at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:807) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor377.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        ... 20 more
```

**Comment by SirBlobman** [comment]
This is caused by Mob Hunting not having an updated WorldGuard handler

**Comment by SlimeDog** [comment]
I thought that was the 7.0 thing. Did I miss something, or not included yet?

**Comment by SlimeDog** [comment]
No, of course not. Apologies.
