### ISSUE TITLE
WorldEdit/WorldGuard vectors generate errors

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#59]
Spigot 1.13.2 latest
CombatLogX 9.0.1.1
Compatibility for WorldGuard 7 v1
worldguard-legacy 7.0.0-b1754
worldedit-bukkit 7.0.0-b3937

Still getting these repeatedly
```
[11:44:28 ERROR]: Could not pass event PlayerMoveEvent to CombatLogX v9.0.1.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:948) ~[spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.PacketPlayInFlying.a(SourceFile:126) ~[spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.util.Location.toVector()Lcom/sk89q/worldedit/Vector;
        at com.SirBlobman.expansion.worldguard7.utility.WGUtil.getLocation(WGUtil.java:87) ~[?:?]
        at com.SirBlobman.expansion.worldguard7.utility.WGUtil.getRegions(WGUtil.java:98) ~[?:?]
        at com.SirBlobman.expansion.worldguard7.utility.WGUtil.allowsPvP(WGUtil.java:103) ~[?:?]
        at com.SirBlobman.expansion.worldguard7.olivolja3.ForceField.isSafeZone(ForceField.java:90) ~[?:?]
        at com.SirBlobman.expansion.worldguard7.olivolja3.ForceField.updateViewedBlocks(ForceField.java:100) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor243.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.2.jar-2018-11-12-1056:git-Spigot-947a8e7-17ff1e0]
        ... 15 more
```

**Comment by SirBlobman** [comment]
@SlimeDog Where did you get that version of WorldEdit/WorldGuard?

The only ones I can find are here:

http://dev.bukkit.org/projects/worldedit/files
http://dev.bukkit.org/projects/worldguard/files

**Comment by SlimeDog** [comment]
As you noted previously:
WE: http://builds.enginehub.org/job/worldedit?branch=master
WG: http://builds.enginehub.org/job/worldguard?branch=master

**Comment by SirBlobman** [comment]
When those become release builds I will add support for them, for now just use the ones on dev.bukkit.org
