### ISSUE TITLE
ConcurrentModificationException in Forcefield extension.

### ISSUE THREAD

**Issue by RealTriassic** [SirBlobman/CombatLogX#595]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

Randomly, this warning is thrown into console:
```
[20:42:35 WARN]: [CombatLogX] Plugin CombatLogX v11.1.0.8.1056 generated an exception while executing task 148
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]
        at java.util.AbstractSet.removeAll(AbstractSet.java:175) ~[?:?]
        at combatlogx.expansion.force.field.task.ForceFieldTask.updateForceField(ForceFieldTask.java:217) ~[?:?]
        at combatlogx.expansion.force.field.task.ForceFieldTask.updateForceField(ForceFieldTask.java:205) ~[?:?]
        at combatlogx.expansion.force.field.task.ForceFieldTask.checkForceField(ForceFieldTask.java:137) ~[?:?]
        at combatlogx.expansion.force.field.task.ForceFieldTask.run(ForceFieldTask.java:67) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1907]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.3.jar:git-Purpur-1907]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

It is caused by Forcefield as far as I can tell.

### Reproduction Steps

I am not sure at the moment unfortunately.

### Expected behaviour

There should be no errors.

### CombatLogX Version

```
[20:45:19 INFO]: 
[20:45:19 INFO]: Java Version: 17.0.6
[20:45:19 INFO]: Java Vendor: Eclipse Adoptium
[20:45:19 INFO]: 
[20:45:19 INFO]: Server Version: git-Purpur-1907 (MC: 1.19.3)
[20:45:19 INFO]: Bukkit Version: 1.19.3-R0.1-SNAPSHOT
[20:45:19 INFO]: Minecraft Version: 1.19.3
[20:45:19 INFO]: NMS Version: 1_19_R2
[20:45:19 INFO]: 
[20:45:19 INFO]: Dependency Information:
[20:45:19 INFO]:  - BlueSlimeCore v2.6.2.239-Beta
[20:45:19 INFO]:  - Citizens v2.0.30-SNAPSHOT (build 2900)
[20:45:19 INFO]:  - Essentials v2.20.0-dev+40-996285c
[20:45:19 INFO]:  - PlaceholderAPI v2.11.2
[20:45:19 INFO]:  - PremiumVanish v2.8.3
[20:45:19 INFO]:  - ProtocolLib v5.0.0-SNAPSHOT-b612
[20:45:19 INFO]:  - WorldGuard v7.0.8-beta-01+cbb2ba7
[20:45:19 INFO]: 
[20:45:19 INFO]: CombatLogX by SirBlobman
[20:45:19 INFO]: Plugin Version: 11.1.0.8.1056
[20:45:19 INFO]: Spigot Version: Not Available
[20:45:19 INFO]: 
[20:45:19 INFO]: Enabled Expansions (4):
[20:45:19 INFO]:  - BossBar
[20:45:19 INFO]:  - CheatPrevention
[20:45:19 INFO]:  - CompatWorldGuard
[20:45:19 INFO]:  - ForceField
[20:45:19 INFO]: 
```

**Comment by SirBlobman** [comment]
@RealTriassic Please send the output from `/clx about ForceField`

**Comment by RealTriassic** [comment]
```
[14:47:52 INFO]: Expansion Information for ForceField:
[14:47:52 INFO]: Display Name: Force Field
[14:47:52 INFO]: Version: 17.1
[14:47:52 INFO]: State: ENABLED
[14:47:52 INFO]: 
[14:47:52 INFO]: Description: 
[14:47:52 INFO]: Authors: olivolja3 (Olivo#3313), SirBlobman
```
