### ISSUE TITLE
plugin stopped working randomly

### ISSUE THREAD

**Issue by Alfa3712** [SirBlobman/CombatLogX#643]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

i uploaded a alreday done lp file but after restart combatlogx stopped working. 

### Reproduction Steps

1. upload a already did lp file
2. restart the server
3. pl should not work now

### Expected behaviour

combatlogx get disabled

### latest log file (if applicable)

[12:51:14 INFO]: [CombatLogX] Enabling CombatLogX v11.2.0.1.1085 [12:51:14 ERROR]: Error occurred while enabling CombatLogX v11.2.0.1.1085 (Is it up to date?) java.lang.NoSuchMethodError: 'void com.github.sirblobman.api.language.LanguageManager.onPluginEnable()'         at com.github.sirblobman.combatlogx.CombatPlugin.onEnable(CombatPlugin.java:92) ~[CombatLogX.jar:?]         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]         at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]         at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]         at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]         at java.lang.Thread.run(Thread.java:833) ~[?:?] [12:51:14 INFO]: [CombatLogX] Disabling CombatLogX v11.2.0.1.1085 [12:51:14 INFO]: [CombatLogX] Disabling expansions... [12:51:14 INFO]: [CombatLogX] There were no expansions to disable. [12:51:14 INFO]: [CombatLogX] Successfully disabled all expansions. [12:51:14 ERROR]: Error occurred while disabling CombatLogX v11.2.0.1.1085 (Is it up to date?) java.lang.NoSuchMethodError: 'void com.github.sirblobman.api.language.LanguageManager.broadcastMessage(java.lang.String, java.lang.String, com.github.sirblobman.api.language.replacer.Replacer[])'         at com.github.sirblobman.combatlogx.CombatPlugin.broadcastDisableMessage(CombatPlugin.java:296) ~[CombatLogX.jar:?]         at com.github.sirblobman.combatlogx.CombatPlugin.onDisable(CombatPlugin.java:117) ~[CombatLogX.jar:?]         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]         at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]         at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]         at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]         at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]         at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]         at java.lang.Thread.run(Thread.java:833) ~[?:?]

### CombatLogX Version

CombatLogX-11.2.0.1.1085 cant run clx cause pl not loading

### Anything else?

error:
[12:51:14 INFO]: [CombatLogX] Enabling CombatLogX v11.2.0.1.1085
[12:51:14 ERROR]: Error occurred while enabling CombatLogX v11.2.0.1.1085 (Is it up to date?)
java.lang.NoSuchMethodError: 'void com.github.sirblobman.api.language.LanguageManager.onPluginEnable()'
        at com.github.sirblobman.combatlogx.CombatPlugin.onEnable(CombatPlugin.java:92) ~[CombatLogX.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:51:14 INFO]: [CombatLogX] Disabling CombatLogX v11.2.0.1.1085
[12:51:14 INFO]: [CombatLogX] Disabling expansions...
[12:51:14 INFO]: [CombatLogX] There were no expansions to disable.
[12:51:14 INFO]: [CombatLogX] Successfully disabled all expansions.
[12:51:14 ERROR]: Error occurred while disabling CombatLogX v11.2.0.1.1085 (Is it up to date?)
java.lang.NoSuchMethodError: 'void com.github.sirblobman.api.language.LanguageManager.broadcastMessage(java.lang.String, java.lang.String, com.github.sirblobman.api.language.replacer.Replacer[])'
        at com.github.sirblobman.combatlogx.CombatPlugin.broadcastDisableMessage(CombatPlugin.java:296) ~[CombatLogX.jar:?]
        at com.github.sirblobman.combatlogx.CombatPlugin.onDisable(CombatPlugin.java:117) ~[CombatLogX.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Alfa3712** [comment]
> 

i m using it

**Comment by Olivoz** [comment]
Could you send the output from /about BlueSlimeCore

**Comment by Alfa3712** [comment]
> Could you send the output from /about BlueSlimeCore

![Screenshot_2023-03-22-19-59-37-26_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/105760302/226936493-cb27d121-71e7-4a6b-8c41-15f2eae8a4a9.jpg)

**Comment by Alfa3712** [comment]
> Is there any chance you could join our discord, so you can send your CombatLogX and BlueSlimeCore jars? Your problem could be caused by malware injecting itself in to the jars and breaking them. I've seen it a couple of times in the past

ok

**Comment by Olivoz** [comment]
Problem was solved in the discord. I was correct, the server had been infected by malware.
