### ISSUE TITLE
Spamming console with error

### ISSUE THREAD

**Issue by Evalutik** [SirBlobman/CombatLogX#646]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

Spamming console with error every time when player killed by player.

Error:
[22:15:47 ERROR]: Could not pass event PlayerDeathEvent to CombatLogX v11.2.0.1.1085
java.lang.NoClassDefFoundError: com/github/sirblobman/api/language/Replacer
	at combatlogx.expansion.rewards.object.Reward.executeCommands(Reward.java:247) ~[?:?]
	at combatlogx.expansion.rewards.object.Reward.tryActivate(Reward.java:153) ~[?:?]
	at combatlogx.expansion.rewards.manager.RewardManager.checkAll(RewardManager.java:42) ~[?:?]
	at combatlogx.expansion.rewards.listener.ListenerRewards.onDeath(ListenerRewards.java:31) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor397.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1912]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:916) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:929) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1535) ~[?:?]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:1001) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1109) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1354) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2235) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$6.a(ServerGamePacketListenerImpl.java:2937) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2859) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]

### Reproduction Steps

Just one player should kill another

### Expected behaviour

Do not spamming console

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/126126362/227745121-672a008d-979b-4655-a149-3318b72644f2.png)

### latest log file (if applicable)

https://drive.google.com/file/d/1lt9pr9PZTxvdOZmmRGEX4IlfLEEzYawW/view?usp=sharing

### CombatLogX Version

[22:25:51 INFO]: 
[22:25:51 INFO]: flJava Version: 719.0.2
[22:25:51 INFO]: flJava Vendor: 7Oracle Corporation
[22:25:51 INFO]: 
[22:25:51 INFO]: flServer Version: 7git-Purpur-1912 (MC: 1.19.3)
[22:25:51 INFO]: flBukkit Version: 71.19.3-R0.1-SNAPSHOT
[22:25:51 INFO]: flMinecraft Version: 71.19.3
[22:25:51 INFO]: flNMS Version: 71_19_R2
[22:25:51 INFO]: 
[22:25:51 INFO]: flDependency Information:
[22:25:51 INFO]: fl - 7BlueSlimeCore v2.7.1.307-Beta
[22:25:51 INFO]: fl - 7Essentials v2.20.0-dev+43-25ad8ac
[22:25:51 INFO]: fl - 7PlaceholderAPI v2.11.2
[22:25:51 INFO]: fl - 7ProtocolLib v5.0.0-SNAPSHOT-b612
[22:25:51 INFO]: fl - 7WorldGuard v7.0.8-beta-01+cbb2ba7
[22:25:51 INFO]: 
[22:25:51 INFO]: flCombatLogX by SirBlobman
[22:25:51 INFO]: flPlugin Version: 711.2.0.1.1085
[22:25:51 INFO]: flSpigot Version: 7Not Available
[22:25:51 INFO]: 
[22:25:51 INFO]: flEnabled Expansions (76fl):
[22:25:51 INFO]: fl - 7ActionBar
[22:25:51 INFO]: fl - 7CheatPrevention
[22:25:51 INFO]: fl - 7CompatEssentialsX
[22:25:51 INFO]: fl - 7CompatPlaceholderAPI
[22:25:51 INFO]: fl - 7Rewards
[22:25:51 INFO]: fl - 7Scoreboard

**Comment by SirBlobman** [comment]
Fixed in Discord.
