### ISSUE TITLE
InvalidPluginException on Paper 1.19.4

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#650]
### Server Implementation

Paper

### Server Version

1.19.4-491

### Describe the bug

CLX failed to load on server start-up

Paper 1.19.4-491
CombatLogX-11.3.0.0.Beta-1093
CLX-ActionBar-11.3.0.0-1093
CLX-BSkyBlock-11.3.0.0-1093
CLX-Citizens-11.3.0.0-1093
CLX-DamageTagger-11.3.0.0-1093
CLX-EssentialX-11.3.0.0-1093
CLX-Logger-11.3.0.0-1093
CLX-LuckPerms-11.3.0.0-1093
CLX-MobTagger-11.3.0.0-1093
CLX-PlaceholderAPI-11.3.0.0-1093
CLX-Residence-11.3.0.0-1093
CLX-WorldGuard-11.3.0.0-1093

### Reproduction Steps

- Update from CLX 11.2.0.1.1086 to CLX 11.3.0.0.Beta-1093, system otherwise identical
- Start server
- Read error in log

### Expected behaviour

Clean start-up

### Screenshots / Videos

```
[11:08:22] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'CombatLogX-11.3.0.0-1093.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/github/sirblobman/api/shaded/bstats/charts/CustomChart
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[paper-1.19.4.jar:git-Paper-491]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.19.4.jar:git-Paper-491]
        at io.papermc.paper.plugin.entrypoint.strategy.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:150) ~[paper-1.19.4.jar:git-Paper-491]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:35) ~[paper-1.19.4.jar:git-Paper-491]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.4.jar:git-Paper-491]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.19.4.jar:git-Paper-491]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.4.jar:git-Paper-491]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-491]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-491]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/github/sirblobman/api/shaded/bstats/charts/CustomChart
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:496) ~[?:?]
        at java.lang.Class.forName(Class.java:475) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.19.4.jar:git-Paper-491]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: com.github.sirblobman.api.shaded.bstats.charts.CustomChart
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:496) ~[?:?]
        at java.lang.Class.forName(Class.java:475) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[paper-1.19.4.jar:git-Paper-491]
        ... 9 more
```

### latest log file (if applicable)

See error above

### CombatLogX Version

Cannot run `clx version` since plugin failed to load, but here is the equivalent information
```
Java Version: 20 
Java Vendor: Oracle Corporation

Server Version: git-Paper-491 (MC: 1.19.4)
Bukkit Version: 1.19.4-R0.1-SNAPSHOT
Minecraft Version: 1.19.4
NMS Version: 1_19_R3 

Dependency Information:
 - BlueSlimeCore v2.7.1.307-Beta
 - BentoBox v1.22.1-SNAPSHOT-b2377
 - Citizens v2.0.31-SNAPSHOT (build 3015)
 - Essentials v2.20.0-dev+50-e7c56b3
 - PlaceholderAPI v2.11.4-DEV-174
 - ProtocolLib v5.0.0-SNAPSHOT-b630
 - Residence v5.1.1.1
 - Sentinel v2.7.3-SNAPSHOT (build 505)
 - WorldGuard v7.0.8-SNAPSHOT+2231-bddfbdd

CombatLogX by SirBlobman
Plugin Version: 11.3.0.0.Beta-1093
Spigot Version: Not Available

Enabled Expansions (10): 
 - ActionBar
 - CompatBSkyBlock
 - CompatCitizens 
 - CompatEssentialsX
 - CompatLuckPerms
 - CompatPlaceholderAPI
 - CompatWorldGuard 
 - DamageTagger
 - Logger 
 - MobTagger
 `



``

### Anything else?

_No response_

**Comment by Olivoz** [comment]
Looks like you forgot to update BlueSlimeCore

**Comment by SlimeDog** [comment]
Indeed. I know the dev deployment instructions stipulating pulling BlueSlimeCore from the zip file, but I forgot, and not for the first time. Perhaps a clearer catch and error message could be implemented.

But all is well now. Thanks.

**Comment by SirBlobman** [comment]
I will look into making an easier catch for outdated dependency versions. Unfortunately, the current plugin.yml loading system doesn't allow us to specify the version of a dependency.

**Comment by SlimeDog** [comment]
Thanks.
