### ISSUE TITLE
Citizens expansion fails to load

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#651]
### Server Implementation

Paper

### Server Version

1.19.4-492

### Describe the bug

Citizens expansion fails to load on server start-up. Previous versions loaded correctly.

### Reproduction Steps

- Update to CLX 11.3.0.0-1093 (previously 11.2.x.x-1086)
- Start server
- Read log

### Expected behaviour

Clean start-up

### Screenshots / Videos

On server start-up
```
java.lang.IllegalStateException: Could not load 'CLX-Citizens-11.3.0.0-1093.jar' from folder 'plugins/CombatLogX/expansions'
        at com.github.sirblobman.combatlogx.api.expansion.ExpansionClassLoader.registerExpansion(ExpansionClassLoader.java:106) ~[CombatLogX-11.3.0.0-1093.jar:?]
        at com.github.sirblobman.combatlogx.api.expansion.ExpansionClassLoader.<init>(ExpansionClassLoader.java:30) ~[CombatLogX-11.3.0.0-1093.jar:?]
        at com.github.sirblobman.combatlogx.api.expansion.ExpansionManager.loadExpansion(ExpansionManager.java:260) ~[CombatLogX-11.3.0.0-1093.jar:?]
        at com.github.sirblobman.combatlogx.api.expansion.ExpansionManager.loadExpansions(ExpansionManager.java:83) ~[CombatLogX-11.3.0.0-1093.jar:?]
        at com.github.sirblobman.combatlogx.CombatPlugin.onLoad(CombatPlugin.java:84) ~[CombatLogX-11.3.0.0-1093.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.19.4.jar:git-Paper-492]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.19.4.jar:git-Paper-492]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:36) ~[paper-1.19.4.jar:git-Paper-492]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.4.jar:git-Paper-492]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.19.4.jar:git-Paper-492]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.4.jar:git-Paper-492]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-492]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-492]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:77) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?]
        at com.github.sirblobman.combatlogx.api.expansion.ExpansionClassLoader.registerExpansion(ExpansionClassLoader.java:100) ~[CombatLogX-11.3.0.0-1093.jar:?]
        ... 13 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.github.sirblobman.combatlogx.api.expansion.ExpansionDescription.getUnlocalizedName()" because "description" is null
        at com.github.sirblobman.combatlogx.api.expansion.Expansion.getName(Expansion.java:114) ~[CombatLogX-11.3.0.0-1093.jar:?]
        at com.github.sirblobman.combatlogx.api.expansion.ExpansionLogger.<init>(ExpansionLogger.java:14) ~[CombatLogX-11.3.0.0-1093.jar:?]
        at com.github.sirblobman.combatlogx.api.expansion.Expansion.getLogger(Expansion.java:64) ~[CombatLogX-11.3.0.0-1093.jar:?]
        at combatlogx.expansion.compatibility.citizens.CitizensExpansion.<init>(CitizensExpansion.java:35) ~[?:?]
        at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:484) ~[?:?]
        at com.github.sirblobman.combatlogx.api.expansion.ExpansionClassLoader.registerExpansion(ExpansionClassLoader.java:100) ~[CombatLogX-11.3.0.0-1093.jar:?]
        ... 13 more
```

### CombatLogX Version

```
> clx version

Java Version: 20 
Java Vendor: Oracle Corporation

Server Version: git-Paper-492 (MC: 1.19.4)
Bukkit Version: 1.19.4-R0.1-SNAPSHOT
Minecraft Version: 1.19.4
NMS Version: 1_19_R3 

Dependency Information:
 - BlueSlimeCore v2.8.0.Beta-310
 - BentoBox v1.22.1-SNAPSHOT-b2377
 - Citizens v2.0.31-SNAPSHOT (build 3015)
 - Essentials v2.20.0-dev+50-e7c56b3
 - PlaceholderAPI v2.11.4-DEV-174
 - ProtocolLib v5.0.0-SNAPSHOT-b630
 - Residence v5.1.1.1
 - Sentinel v2.7.3-SNAPSHOT (build 505)
 - WorldGuard v7.0.8-SNAPSHOT+2231-bddfbdd

CombatLogX by SirBlobman
Plugin Version: 11.3.0.0.Beta-1093
Spigot Version: Not Available

Enabled Expansions (9):
 - ActionBar
 - CompatBSkyBlock
 - CompatEssentialsX
 - CompatLuckPerms
 - CompatPlaceholderAPI
 - CompatWorldGuard 
 - DamageTagger
 - Logger 
 - MobTagger
```

**Comment by SlimeDog** [comment]
Confirmed fixed with CombatLogX-11.3.0.0-1102. Thanks.
