### ISSUE TITLE
BlueSlimeCore incompatibility

### ISSUE THREAD

**Issue by SlimeDog** [SirBlobman/CombatLogX#661]
### Server Implementation

Paper

### Server Version

1.19.4-519

### Describe the bug

CombatLogX v11.3.0.0.Beta-1109
BlueSlimeCore 2.8.0-b326

On server start-up
```
[23:23:44] [Server thread/ERROR]: Error occurred while enabling CombatLogX v11.3.0.0.Beta-1109 (Is it up to date?)
java.lang.NoSuchMethodError: 'com.github.sirblobman.api.update.UpdateManager com.github.sirblobman.api.core.CorePlugin.getUpdateManager()'
        at com.github.sirblobman.combatlogx.CombatPlugin.registerUpdates(CombatPlugin.java:290) ~[CombatLogX-11.3.0.0-b1109.jar:?]
        at com.github.sirblobman.combatlogx.CombatPlugin.onEnable(CombatPlugin.java:118) ~[CombatLogX-11.3.0.0-b1109.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-519]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-519]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555) ~[paper-1.19.4.jar:git-Paper-519]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-519]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-519]
```

### Reproduction Steps

- Update BlueSlimeCore from 2.8.0.Beta-315 to 2.8.0.Beta-326
- Start server
- Read log

### Expected behaviour

Compatibility with BlueSlimeCore

### CombatLogX Version

v11.3.0.0.Beta-1109

**Comment by SlimeDog** [comment]
and BlueSlimeCore 2.8.0-b327

**Comment by SirBlobman** [comment]
Thanks for the report. This is caused by the new update system that I'm still working on.

(UpdateManager --> SpigotUpdateManager and HangarUpdateManager)

**Comment by SlimeDog** [comment]
Confirmed fixed via CLX b1110. Thanks.
