### ISSUE TITLE
NPC Null Drops Error

### ISSUE THREAD

**Issue by successed** [SirBlobman/CombatLogX#69]
[21:56:21] [Server thread/ERROR]: Could not pass event NPCDeathEvent to CombatLogX v9.4.1.0
java.lang.IllegalArgumentException: Cannot drop a Null item.
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.13.2.jar:git-Paper-572]
	at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.dropItem(CraftWorld.java:347) ~[patched_1.13.2.jar:git-Paper-572]
	at com.SirBlobman.expansion.compatcitizens.listener.NPCManager.lambda$onNPCDeath$1(NPCManager.java:171) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_201]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_201]
	at com.SirBlobman.expansion.compatcitizens.listener.NPCManager.onNPCDeath(NPCManager.java:171) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor723.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-572]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-572]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-572]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-572]
	at net.citizensnpcs.EventListen.onEntityDeath(EventListen.java:248) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor343.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-572]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-572]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-572]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-572]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:632) ~[patched_1.13.2.jar:git-Paper-572]
	at net.minecraft.server.v1_13_R2.EntityPlayer.die(EntityPlayer.java:513) ~[patched_1.13.2.jar:git-Paper-572]
	at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.die(EntityHumanNPC.java:178) ~[?:?]
	at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1088) ~[patched_1.13.2.jar:git-Paper-572]
	at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity(EntityHuman.java:817) ~[patched_1.13.2.jar:git-Paper-572]
	at net.minecraft.server.v1_13_R2.EntityPlayer.damageEntity(EntityPlayer.java:658) ~[patched_1.13.2.jar:git-Paper-572]
	at net.citizensnpcs.nms.v1_13_R2.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:152) ~[?:?]
	at net.minecraft.server.v1_13_R2.EntityHuman.attack(EntityHuman.java:1082) ~[patched_1.13.2.jar:git-Paper-572]
	at net.minecraft.server.v1_13_R2.EntityPlayer.attack(EntityPlayer.java:1446) ~[patched_1.13.2.jar:git-Paper-572]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:2010) ~[patched_1.13.2.jar:git-Paper-572]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.13.2.jar:git-Paper-572]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.13.2.jar:git-Paper-572]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-572]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-572]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-572]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-572]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-572]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-572]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by SirBlobman** [comment]
Should be fixed in 9.4.1.2
