### ISSUE TITLE
Entry prevention expansion not working.

### ISSUE THREAD

**Issue by benjaramire3** [SirBlobman/CombatLogX#812]
### Server Implementation

Spigot

### Server Version

other

### Describe the bug

[18:37:51 ERROR]: Could not pass event BlockBreakEvent to CombatLogX v11.4.0.1.1193
java.lang.IllegalArgumentException: Unsupported material with no data value: SHORT_GRASS
        at com.github.sirblobman.api.shaded.xseries.XMaterial.lambda$matchXMaterial$0(XMaterial.java:1817) ~[BlueSlimeCore.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at com.github.sirblobman.api.shaded.xseries.XMaterial.matchXMaterial(XMaterial.java:1817) ~[BlueSlimeCore.jar:?]
        at combatlogx.expansion.cheat.prevention.listener.ListenerBlocks.fetchMaterial(ListenerBlocks.java:111) ~[?:?]
        at combatlogx.expansion.cheat.prevention.listener.ListenerBlocks.onBreak(ListenerBlocks.java:52) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor335.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-354]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-354]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-354]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:375) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:334) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:272) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1847) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-354]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1458) ~[paper-1.20.4.jar:git-Paper-354]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-354]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1435) ~[paper-1.20.4.jar:git-Paper-354]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[paper-1.20.4.jar:git-Paper-354]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[paper-1.20.4.jar:git-Paper-354]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper-1.20.4.jar:git-Paper-354]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-354]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

### Reproduction Steps

1 install the plugin
2 install expansions
3 jump error

### Expected behaviour

What I was hoping would happen is that I wouldn't get that error.

### CombatLogX Version

11.4.0.1.1193

**Comment by Olivoz** [comment]
The version of CombatLogX you're running does not support 1.20.4. Update to the latest beta build on our [jenkins](https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX/job/main/)

**Comment by benjaramire3** [comment]
How do I get it to push me out of the pvp zones if the expansion doesn't work?

**Comment by SirBlobman** [comment]
Which expansion is not working and what have you tried so far?

**Comment by SirBlobman** [comment]
@benjaramire3 Since there is no response I am closing this.
