### ISSUE TITLE
Random error on my console

### ISSUE THREAD

**Issue by MrPungle** [SirBlobman/CombatLogX#82]
`This error randomly shows up on the console and idk why 

[06:17:21 WARN]: [CombatLogX] Plugin CombatLogX v9.8.4.0 generated an exception while executing task 5747
java.lang.IllegalArgumentException: commands cannot be empty or NULL!
        at org.apache.commons.lang.Validate.notEmpty(Validate.java:248) ~[patched_1.12.2.jar:git-Paper-1618]
        at com.SirBlobman.expansion.rewards.config.Reward.<init>(Reward.java:24) ~[?:?]
        at com.SirBlobman.expansion.rewards.config.ConfigRewards.getRewards(ConfigRewards.java:60) ~[?:?]
        at com.SirBlobman.expansion.rewards.Rewards.lambda$onDeath$0(Rewards.java:57) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
`

**Minecraft Version**
PaperSpigot 1.12.2 (1618)

**CombatLogX Version:**
CombatLogX 9.8.4.0

**Comment by SirBlobman** [comment]
You modified your Rewards config and made it invalid. If you don't need the expansion just delete the jar
