### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by Byron747** [SirBlobman/CombatLogX#836]
### Server Implementation

Spigot

### Server Version

1.21

### Describe the bug

[21:21:10 ERROR]: Could not pass event PlayerInteractEntityEvent to CombatLogX v11.5.0.0.1242
java.lang.IllegalAccessError: class combatlogx.expansion.cheat.prevention.listener.ListenerEntities tried to access protected method 'com.github.sirblobman.api.configuration.ConfigurationManager com.github.sirblobman.combatlogx.api.expansion.Expansion.getConfigurationManager()' (combatlogx.expansion.cheat.prevention.listener.ListenerEntities is in unnamed module of loader com.github.sirblobman.combatlogx.api.expansion.ExpansionClassLoader @401bb078; com.github.sirblobman.combatlogx.api.expansion.Expansion is in unnamed module of loader 'CombatLogX.jar' @4bdc91d1)
        at combatlogx.expansion.cheat.prevention.listener.ListenerEntities.getConfiguration(ListenerEntities.java:30) ~[?:?]
        at combatlogx.expansion.cheat.prevention.listener.ListenerEntities.isEnabled(ListenerEntities.java:35) ~[?:?]
        at combatlogx.expansion.cheat.prevention.listener.ListenerEntities.onInteract(ListenerEntities.java:20) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1384.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:60) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.performInteraction(ServerGamePacketListenerImpl.java:2834) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.a(ServerGamePacketListenerImpl.java:2884) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.dispatch(ServerboundInteractPacket.java:138) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:89) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2823) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:76) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:14) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:35) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:152) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1562) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:190) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1540) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1533) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[?:?]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1491) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1498) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1345) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[leaf-1.21.jar:1.21-DEV-b2692f7]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Reproduction Steps

as

### Expected behaviour

as

### Screenshots / Videos

as

### latest log file (if applicable)

as

### CombatLogX Version

11.5.0.0.1242

### Anything else?

I recently updated to version 1.21 and it gives me this error

**Comment by SirBlobman** [comment]
Sounds like you used `/reload` or a Plugman variant. Please do a proper restart and send the full `/logs/latest.log` file.

> `unnamed module of loader `
