### ISSUE TITLE
Combatlogx also gives an error in the console

### ISSUE THREAD

**Issue by moreoss** [SirBlobman/CombatLogX#845]
### Server Implementation

Paper

### Server Version

other

### Describe the bug

It sends an error like this to the log console.

[17:55:48 WARN]: [CombatLogX] Plugin CombatLogX v11.1.0.7.1025 generated an exception while executing task 1449
java.lang.NullPointerException: Cannot invoke "com.github.sirblobman.combatlogx.api.object.CombatTag.getTagType()" because "combatTag" is null
        at com.github.sirblobman.combatlogx.api.object.TagInformation.getTagTypes(TagInformation.java:170) ~[?:?]
        at com.github.sirblobman.combatlogx.api.object.TagInformation.getCurrentTagType(TagInformation.java:179) ~[?:?]
        at combatlogx.expansion.compatibility.region.world.guard.handler.WorldGuardRegionHandler.isSafeZone(WorldGuardRegionHandler.java:40) ~[?:?]
        at combatlogx.expansion.force.field.task.ForceFieldTask.isSafe(ForceFieldTask.java:172) ~[?:?]
        at combatlogx.expansion.force.field.task.ForceFieldTask.getForceFieldArea(ForceFieldTask.java:289) ~[?:?]
        at combatlogx.expansion.force.field.task.ForceFieldTask.updateForceField(ForceFieldTask.java:210) ~[?:?]
        at combatlogx.expansion.force.field.task.ForceFieldTask.updateForceField(ForceFieldTask.java:205) ~[?:?]
        at combatlogx.expansion.force.field.task.ForceFieldTask.checkForceField(ForceFieldTask.java:137) ~[?:?]
        at combatlogx.expansion.force.field.task.ForceFieldTask.run(ForceFieldTask.java:67) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]

### Reproduction Steps

There's no need

### Expected behaviour

Correction of the problem

### Screenshots / Videos

There's no need

### latest log file (if applicable)

https://s6.dosya.tc/server21/qnwn8z/latest.rar.html

### CombatLogX Version

11.1.0.7.1025

### Anything else?

There's no need

**Comment by Olivoz** [comment]
Your CombatLogX version is out of date. See if updating solves your issue. Also please follow the issue template and provide the *entire* output from `/clx version`

**Comment by moreoss** [comment]
[19:18:53 INFO]:
[19:18:53 INFO]: Java Version: 16.0.1
[19:18:53 INFO]: Java Vendor: Private Build
[19:18:53 INFO]:
[19:18:53 INFO]: Server Version: git-Paper-794 (MC: 1.16.5)
[19:18:53 INFO]: Bukkit Version: 1.16.5-R0.1-SNAPSHOT
[19:18:53 INFO]: Minecraft Version: 1.16.5
[19:18:53 INFO]: NMS Version: 1_16_R3
[19:18:53 INFO]:
[19:18:53 INFO]: Dependency Information:
[19:18:53 INFO]:  - BlueSlimeCore v2.6.1.222-Beta
[19:18:53 INFO]:  - AngelChest v9.7.0
[19:18:53 INFO]:  - Citizens v2.0.30-SNAPSHOT (build 2890)
[19:18:53 INFO]:  - Essentials v2.19.7
[19:18:53 INFO]:  - GriefPrevention v16.14.0
[19:18:53 INFO]:  - MythicMobs v5.2.0-038019e5
[19:18:53 INFO]:  - PlaceholderAPI v2.11.2
[19:18:53 INFO]:  - ProtocolLib v5.1.0
[19:18:53 INFO]:  - WorldGuard v7.0.4+f7ff984
[19:18:53 INFO]:  - ViaVersion v4.6.2
[19:18:53 INFO]:
[19:18:53 INFO]: CombatLogX by SirBlobman
[19:18:53 INFO]: Plugin Version: 11.1.0.7.1025
[19:18:53 INFO]: Spigot Version: 11.5.0.0.1242
[19:18:53 INFO]:
[19:18:53 INFO]: Enabled Expansions (5):
[19:18:53 INFO]:  - ActionBar
[19:18:53 INFO]:  - CheatPrevention
[19:18:53 INFO]:  - CompatGriefPrevention
[19:18:53 INFO]:  - CompatWorldGuard
[19:18:53 INFO]:  - ForceField

**Comment by SirBlobman** [comment]
Update plugin and expansions.

**Comment by moreoss** [comment]
our base version is 1.16.5 this plugin supports version 1.19.4

**Comment by SirBlobman** [comment]
1.16.5 is untested. I do not have time to test every possible version, therefore I only check if it works on the most recent ones (e.g. 1.19.4, 1.20.6, 1.21.1)

I have not removed code for 1.16.5 yet, however I do recommend keeping your server updated.

Please update the plugins and the expansions

**Comment by moreoss** [comment]
I do not want to upgrade my server's base version to 1.16.5 and above. I request a correction for this.

**Comment by SirBlobman** [comment]
> I do not want to upgrade my server's base version to 1.16.5 and above. I request a correction for this.

Please update the CombatLogX version and expansions as requested. Then report if any further issues occur and we will fix those.

**Comment by moreoss** [comment]
Hello, I'm sorry I looked so late.
I sent you a video recording, the worldguard setting is not working
[video.zip](https://github.com/user-attachments/files/17203674/video.zip)

**Comment by Olivoz** [comment]
The use pvp flag setting is broken from what I've seen reported, I recommend you open a separate issue for that. For a fix set the player-combat flag to deny.

**Comment by moreoss** [comment]
"use-pvp-flag: false" Should I do it like this?
