### ISSUE TITLE
Could not pass event PlayerReTagEvent to CombatLogX v11.5.0.0.1242

### ISSUE THREAD

**Issue by Melon-Oof** [SirBlobman/CombatLogX#852]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

In the console the following error is "spammed"/sent multiple times in matters of seconds

### Reproduction Steps

Install CLX on 1.21 ( This server is running Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT) )

Hit someone.

### Expected behaviour

Not to show this error

### Screenshots / Videos

[06:45:23 ERROR]: Could not pass event PlayerReTagEvent to CombatLogX v11.5.0.0.1242
java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
        at combatlogx.expansion.cheat.prevention.listener.ListenerInventories.onReTag(ListenerInventories.java:43) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor301.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.manager.CombatManager.tag(CombatManager.java:100) ~[CombatLogX.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.manager.CombatManager.tag(CombatManager.java:65) ~[CombatLogX.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.listener.ListenerDamage.checkTag(ListenerDamage.java:134) ~[CombatLogX.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.listener.ListenerDamage.onDamage(ListenerDamage.java:44) ~[CombatLogX.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor273.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:275) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1207) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1197) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1127) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1090) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1245) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2327) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1488) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1002) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1205) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:452) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:274) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:239) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:218) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.AbstractArrow.preHitTargetOrDeflectSelf(AbstractArrow.java:341) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:270) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:76) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1248) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1420) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[06:45:23 ERROR]: Could not pass event PlayerReTagEvent to CombatLogX v11.5.0.0.1242
java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
        at combatlogx.expansion.cheat.prevention.listener.ListenerInventories.onReTag(ListenerInventories.java:43) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor301.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.manager.CombatManager.tag(CombatManager.java:100) ~[CombatLogX.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.manager.CombatManager.tag(CombatManager.java:65) ~[CombatLogX.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.listener.ListenerDamage.checkTag(ListenerDamage.java:134) ~[CombatLogX.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.listener.ListenerDamage.onDamage(ListenerDamage.java:45) ~[CombatLogX.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor273.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:275) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1207) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1197) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1127) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1090) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1245) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2327) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1488) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1002) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1205) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:452) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:274) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:239) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:218) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.AbstractArrow.preHitTargetOrDeflectSelf(AbstractArrow.java:341) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:270) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:76) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1248) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1420) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[06:45:29 ERROR]: Could not pass event PlayerReTagEvent to CombatLogX v11.5.0.0.1242
java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
        at combatlogx.expansion.cheat.prevention.listener.ListenerInventories.onReTag(ListenerInventories.java:43) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor301.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.manager.CombatManager.tag(CombatManager.java:100) ~[CombatLogX.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.manager.CombatManager.tag(CombatManager.java:65) ~[CombatLogX.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.listener.ListenerDamage.checkTag(ListenerDamage.java:134) ~[CombatLogX.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.listener.ListenerDamage.onDamage(ListenerDamage.java:44) ~[CombatLogX.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor273.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:275) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1207) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1197) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1127) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1090) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1245) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2327) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1488) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1002) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1205) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:452) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:274) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:239) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:218) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.AbstractArrow.preHitTargetOrDeflectSelf(AbstractArrow.java:341) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:270) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:76) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1248) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1420) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[06:45:29 ERROR]: Could not pass event PlayerReTagEvent to CombatLogX v11.5.0.0.1242
java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
        at combatlogx.expansion.cheat.prevention.listener.ListenerInventories.onReTag(ListenerInventories.java:43) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor301.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.manager.CombatManager.tag(CombatManager.java:100) ~[CombatLogX.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.manager.CombatManager.tag(CombatManager.java:65) ~[CombatLogX.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.listener.ListenerDamage.checkTag(ListenerDamage.java:134) ~[CombatLogX.jar:?]
        at CombatLogX.jar/com.github.sirblobman.combatlogx.listener.ListenerDamage.onDamage(ListenerDamage.java:45) ~[CombatLogX.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor273.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:275) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1207) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1197) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1127) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1090) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1245) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2327) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1488) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1002) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1205) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:452) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:274) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:239) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:218) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.AbstractArrow.preHitTargetOrDeflectSelf(AbstractArrow.java:341) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:270) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:76) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1248) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1420) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### CombatLogX Version

11.5.0.0.1242

### Anything else?

[latest.log](https://github.com/user-attachments/files/17089305/latest.log)

**Comment by Olivoz** [comment]
This has already been fixed in beta builds. If you do not want to update disable the [inventory closing](https://github.com/SirBlobman/CombatLogX/blob/420cf12d722755460e73a76b689209f08162d823/expansion/cheat-prevention/src/main/resources/inventories.yml#L3) feature of the Cheat Prevention expansion.

Related to #837, #839, #847 and #851
