### ISSUE TITLE
CheatPrevention Error

### ISSUE THREAD

**Issue by nightmvre** [SirBlobman/CombatLogX#855]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

Massive Error spam in console

### Reproduction Steps

Use CheatPrevention

### Expected behaviour

No massive errors in console

### Screenshots / Videos

[21:37:31 ERROR]: Could not pass event PlayerReTagEvent to CombatLogX v11.5.0.0.1242
java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
        at combatlogx.expansion.cheat.prevention.listener.ListenerInventories.onReTag(ListenerInventories.java:43) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1306.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2312-d7a7c91]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at CombatLogX-1727401002520.jar/com.github.sirblobman.combatlogx.manager.CombatManager.tag(CombatManager.java:100) ~[CombatLogX-1727401002520.jar:?]
        at CombatLogX-1727401002520.jar/com.github.sirblobman.combatlogx.manager.CombatManager.tag(CombatManager.java:65) ~[CombatLogX-1727401002520.jar:?]
        at combatlogx.expansion.mob.tagger.listener.ListenerDamage.checkTag(ListenerDamage.java:200) ~[?:?]
        at combatlogx.expansion.mob.tagger.listener.ListenerDamage.onDamage(ListenerDamage.java:76) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1352.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2312-d7a7c91]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:277) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1219) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1209) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1138) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1101) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1257) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2420) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1553) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1041) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1235) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:453) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:301) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:266) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:245) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.world.entity.projectile.AbstractArrow.preHitTargetOrDeflectSelf(AbstractArrow.java:342) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:271) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:76) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1330) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:761) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:738) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1842) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1633) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1333) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2312-d7a7c91]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### CombatLogX Version

11.5.0.0.1242

**Comment by Olivoz** [comment]
This has already been fixed in beta builds. If you do not want to update disable the [inventory closing](https://github.com/SirBlobman/CombatLogX/blob/420cf12d722755460e73a76b689209f08162d823/expansion/cheat-prevention/src/main/resources/inventories.yml#L3) feature of the Cheat Prevention expansion.

Related to #837, #839, #847 and #851
