### ISSUE TITLE
1.21.1 Error

### ISSUE THREAD

**Issue by frknmrl** [SirBlobman/CombatLogX#857]
### Server Implementation

Paper

### Server Version

1.21.1

### Describe the bug

[20:22:56] [Server thread/ERROR]: Could not pass event PlayerReTagEvent to CombatLogX v11.5.0.0.1242
java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
	at combatlogx.expansion.cheat.prevention.listener.ListenerInventories.onReTag(ListenerInventories.java:43) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor736.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-105-b7ab22d]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at CombatLogX.jar/com.github.sirblobman.combatlogx.manager.CombatManager.tag(CombatManager.java:100) ~[CombatLogX.jar:?]
	at CombatLogX.jar/com.github.sirblobman.combatlogx.manager.CombatManager.tag(CombatManager.java:65) ~[CombatLogX.jar:?]
	at CombatLogX.jar/com.github.sirblobman.combatlogx.listener.ListenerDamage.checkTag(ListenerDamage.java:134) ~[CombatLogX.jar:?]
	at CombatLogX.jar/com.github.sirblobman.combatlogx.listener.ListenerDamage.onDamage(ListenerDamage.java:45) ~[CombatLogX.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor706.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-105-b7ab22d]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:277) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1209) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1199) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1129) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1092) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1247) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2327) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1474) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:1002) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1205) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:452) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:271) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:236) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:215) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.world.entity.projectile.AbstractArrow.preHitTargetOrDeflectSelf(AbstractArrow.java:341) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:270) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:76) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1248) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1420) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1804) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-105-b7ab22d]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]

### Reproduction Steps

This error is being spawned while the players are hitting each other

### Expected behaviour

.

### CombatLogX Version

![Screenshot_1](https://github.com/user-attachments/assets/b654448b-728d-44f3-9ad5-665ea741e90b)

**Comment by Olivoz** [comment]
This has already been fixed in beta builds. If you do not want to update disable the [inventory closing](https://github.com/SirBlobman/CombatLogX/blob/420cf12d722755460e73a76b689209f08162d823/expansion/cheat-prevention/src/main/resources/inventories.yml#L3) feature of the Cheat Prevention expansion.

Related to #837, #839, #847, #851, #855 and #856
