### ISSUE TITLE
Error during the start of the fight.

### ISSUE THREAD

**Issue by JakubMarkiewicz06** [SirBlobman/CombatLogX#863]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

When I start a fight I get an error in the console. Version 1.21.1 purpur.

### Reproduction Steps

Every time I start a fight this error appears.

### Expected behaviour

no error should occur.

### latest log file (if applicable)

[00:35:09 INFO]: Jakub6666 issued server command: /tag Jakub6666 [00:35:18 ERROR]: Could not pass event PlayerTagEvent to CombatLogX v11.5.0.0.1242 java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected         at combatlogx.expansion.cheat.prevention.listener.ListenerInventories.onTag(ListenerInventories.java:29) ~[?:?]         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor377.execute(Unknown Source) ~[?:?]         at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2324-e12a4de]         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]         at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]         at CombatLogX.jar/com.github.sirblobman.combatlogx.manager.CombatManager.tag(CombatManager.java:108) ~[CombatLogX.jar:?]         at CombatLogX.jar/com.github.sirblobman.combatlogx.manager.CombatManager.tag(CombatManager.java:65) ~[CombatLogX.jar:?]         at CombatLogX.jar/com.github.sirblobman.combatlogx.command.combatlogx.SubCommandTag.execute(SubCommandTag.java:65) ~[CombatLogX.jar:?]         at BlueSlimeCore-2.9.6.431.jar/com.github.sirblobman.api.command.Command.onCommand(Command.java:493) ~[BlueSlimeCore-2.9.6.431.jar:?]         at BlueSlimeCore-2.9.6.431.jar/com.github.sirblobman.api.command.Command.onCommand(Command.java:484) ~[BlueSlimeCore-2.9.6.431.jar:?]         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]         at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]         at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.commands.Commands.performCommand(Commands.java:358) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2297) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2271) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2324-e12a4de]         at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### CombatLogX Version

11.5.0.0.1242

**Comment by Olivoz** [comment]
This has already been fixed in beta builds. If you do not want to update disable the [inventory closing](https://github.com/SirBlobman/CombatLogX/blob/420cf12d722755460e73a76b689209f08162d823/expansion/cheat-prevention/src/main/resources/inventories.yml#L3) feature of the Cheat Prevention expansion.

Related to #837, #839, #847, #851, #852, #855, #856 and #857
