### ISSUE TITLE
Error Spam in Server Console

### ISSUE THREAD

**Issue by Scratchycarl** [SirBlobman/CombatLogX#865]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

 [Sun 16:41:38 ERROR Minecraft] Could not pass event PlayerReTagEvent to CombatLogX v11.5.0.0.1242
java.lang.IncompatibleClassChangeError: Found interface org.bukkit.inventory.InventoryView, but class was expected
    at combatlogx.expansion.cheat.prevention.listener.ListenerInventories.onReTag(ListenerInventories.java:43)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor115.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630)
    at CombatLogX.jar//com.github.sirblobman.combatlogx.manager.CombatManager.tag(CombatManager.java:100)
    at CombatLogX.jar//com.github.sirblobman.combatlogx.manager.CombatManager.tag(CombatManager.java:65)
    at combatlogx.expansion.mob.tagger.listener.ListenerDamage.checkTag(ListenerDamage.java:200)
    at combatlogx.expansion.mob.tagger.listener.ListenerDamage.onDamage(ListenerDamage.java:77)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor159.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630)
    at org.bukkit.craftbukkit.event.CraftEventFactory.call

### Reproduction Steps

The error shows on startup.

### Expected behaviour

Kept spamming the console.

### CombatLogX Version

v11.5.0.0.1242

**Comment by Olivoz** [comment]
This has already been fixed in beta builds. If you do not want to update disable the [inventory closing](https://github.com/SirBlobman/CombatLogX/blob/420cf12d722755460e73a76b689209f08162d823/expansion/cheat-prevention/src/main/resources/inventories.yml#L3) feature of the Cheat Prevention expansion.

Related to #837, #839, #847, #851, #852, #855, #856, #857 and #863

**Comment by Scratchycarl** [comment]
Got it, thanks. My players are reporting that they are getting tagged for fall damage. How can I fix that? Thanks a lot!

**Comment by Olivoz** [comment]
Depending on your needs remove or configure the Damage Tagger expansion. For smaller questions like this I recommend joining our [discord](https://discord.gg/XMq2agT) or using the [discussions tab](https://github.com/SirBlobman/CombatLogX/discussions).
