### ISSUE TITLE
NoSuchFieldError in CombatLogX - ENDER_CRYSTAL field missing

### ISSUE THREAD

**Issue by KuldeepB19** [SirBlobman/CombatLogX#867]
### Server Implementation

Paper

### Server Version

other

### Describe the bug

Minecraft Version: Paper 1.21.3 (Build #25)
CombatLogX Version: v11.5.0.0.1242

First of all, I would like to thank you for your outstanding work on CombatLogX. It's a fantastic plugin and I really appreciate the time and effort you've invested in maintaining and updating it.

But today I encountered a NoSuchFieldError in the CombatLogX plugin when placing an entity. The error occurs due to the plugin attempting to access a non-existent field ENDER_CRYSTAL in the org.bukkit.entity.EntityType class. It seems that the reference to ENDER_CRYSTAL in the plugin code is no longer valid in the version of Paper I am using.

### Reproduction Steps

Steps to Reproduce:

Install CombatLogX v11.5.0.0.1242 on a Paper 1.21.3 server.
Try placing an entity (specifically an Ender Crystal).
The following error is logged in the console.

### Expected behaviour

Expected Behavior: The plugin should handle the EntityPlaceEvent without errors, properly referencing the EntityType fields that are available in Paper 1.21.3.

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/73dbde75-fa03-4dd1-8963-a9a6c69a384c)

error message in console:

[17:37:10 ERROR]: Could not pass event EntityPlaceEvent to CombatLogX v11.5.0.0.1242
java.lang.NoSuchFieldError: Class org.bukkit.entity.EntityType does not have member field 'org.bukkit.entity.EntityType ENDER_CRYSTAL'
        at combatlogx.expansion.endcrystals.ListenerCrystals_Modern.onPlace(ListenerCrystals_Modern.java:32) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor219.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityPlaceEvent(CraftEventFactory.java:501) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.world.item.BoatItem.use(BoatItem.java:79) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.world.item.ItemStack.use(ItemStack.java:612) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.server.level.ServerPlayerGameMode.useItem(ServerPlayerGameMode.java:486) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2051) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:47) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:10) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1576) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1553) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1546) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1497) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1507) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1343) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-25-1ef4c0e]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### CombatLogX Version

clx version
[17:40:18 INFO]: Java Version: 21.0.2
[17:40:18 INFO]: Java Vendor: GraalVM Community
[17:40:18 INFO]: Java URL: N/A
[17:40:18 INFO]: Server Version: 1.21.3-25-1ef4c0e (MC: 1.21.3)
[17:40:18 INFO]: Bukkit Version: 1.21.3-R0.1-SNAPSHOT
[17:40:18 INFO]: Minecraft Version: 1.21.3
[17:40:18 INFO]: NMS Version: Unsupported
[17:40:18 INFO]: Dependency Information:
[17:40:18 INFO]:  - AngelChest (not installed)
[17:40:18 INFO]:  - ASkyBlock (not installed)
[17:40:18 INFO]:  - BentoBox (not installed)
[17:40:18 INFO]:  - Citizens (not installed)
[17:40:18 INFO]:  - CMI (not installed)
[17:40:18 INFO]:  - CrackShot (not installed)
[17:40:18 INFO]:  - CrashClaim (not installed)
[17:40:18 INFO]:  - Essentials (not installed)
[17:40:18 INFO]:  - FabledSkyBlock (not installed)
[17:40:18 INFO]:  - FeatherBoard (not installed)
[17:40:18 INFO]:  - FlagWar (not installed)
[17:40:18 INFO]:  - GriefDefender (not installed)
[17:40:18 INFO]:  - GriefPrevention (not installed)
[17:40:18 INFO]:  - HuskHomes (not installed)
[17:40:18 INFO]:  - HuskSync (not installed)
[17:40:18 INFO]:  - HuskTowns (not installed)
[17:40:18 INFO]:  - iDisguise (not installed)
[17:40:18 INFO]:  - IridiumSkyblock (not installed)
[17:40:18 INFO]:  - Kingdoms (not installed)
[17:40:18 INFO]:  - Konquest (not installed)
[17:40:18 INFO]:  - Lands (not installed)
[17:40:18 INFO]:  - LibsDisguises (not installed)
[17:40:18 INFO]:  - MarriageMaster (not installed)
[17:40:18 INFO]:  - MCPets (not installed)
[17:40:18 INFO]:  - MythicMobs (not installed)
[17:40:18 INFO]:  - PlaceholderAPI (not installed)
[17:40:18 INFO]:  - PlayerParticles (not installed)
[17:40:18 INFO]:  - PreciousStones (not installed)
[17:40:18 INFO]:  - PremiumVanish (not installed)
[17:40:18 INFO]:  - ProtectionStones (not installed)
[17:40:18 INFO]:  - ProtocolLib v5.3.0
[17:40:18 INFO]:  - RedProtect (not installed)
[17:40:18 INFO]:  - Residence (not installed)
[17:40:18 INFO]:  - Sentinel (not installed)
[17:40:18 INFO]:  - SuperiorSkyblock2 (not installed)
[17:40:18 INFO]:  - SuperVanish (not installed)
[17:40:18 INFO]:  - Towny (not installed)
[17:40:18 INFO]:  - UltimateClaims (not installed)
[17:40:18 INFO]:  - uSkyBlock (not installed)
[17:40:18 INFO]:  - VanishNoPacket (not installed)
[17:40:18 INFO]:  - WorldGuard (not installed)
[17:40:18 INFO]:  - ViaVersion v5.1.1
[17:40:18 INFO]:  - BlueSlimeCore v2.9.6.431
[17:40:18 INFO]: CombatLogX by SirBlobman
[17:40:18 INFO]: Local Version: 11.5.0.0.1242
[17:40:18 INFO]: Remote Version: 11.5.0.0.1242
[17:40:18 INFO]: Enabled Expansions (6):
[17:40:18 INFO]:  - Action Bar v17.3
[17:40:18 INFO]:  - Cheat Prevention v17.7
[17:40:18 INFO]:  - LuckPerms Compatibility v17.1
[17:40:18 INFO]:  - Damage Tagger v17.1
[17:40:18 INFO]:  - End Crystal Helper v17.1
[17:40:18 INFO]:  - Logger v17.3

### Anything else?

I am not very experienced with your plugin or coding plugins in general so this is the best I could report, there are many expansions not installed cos I deleted them (as I did not require them). 
Also I know that it's not yet officially tested and released on 1.21.3, but kindly help me solve it if possible.
Thanks a lot!!

**Comment by Olivoz** [comment]
Thank you for reporting the issue. It should already be fixed in the latest beta build of CombatLogX available on the [Jenkins](https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX/job/main). Could you test it and see if it solves your problem? If you do so make sure to update the expansions as well.

**Comment by KuldeepB19** [comment]
Hey, Sorry for the late response. I really appreciate your quick response and solution. I will update and test the new version of the plugin and let you know ASAP!

**Comment by OperVaite** [comment]
On the latest version with Jenkins the problem is relevant, the Paper server version is 1.21.4

![Image](https://github.com/user-attachments/assets/06940554-a8b5-40ed-844d-b8432223b689)

**Comment by Olivoz** [comment]
> On the latest version with Jenkins the problem is relevant, the Paper server version is 1.21.4

Make sure you updated the expansions together with the main jar (and BlueSlimeCore). You're most likely running the old EndCrystals expansion.

**Comment by SirBlobman** [comment]
This issue should be fixed as long as all expansions are updated correctly. Please reopen this if that's not the case.
