### ISSUE TITLE
End Crystal Helper

### ISSUE THREAD

**Issue by wchtig** [SirBlobman/CombatLogX#869]
### Server Implementation

Paper

### Server Version

1.21

### Describe the bug

End Crystal Helper doesnt work. When you place a endcrystal, this error comes:

"[12:28:12 ERROR]: Could not pass event EntityPlaceEvent to CombatLogX v11.5.0.0.1242
java.lang.NoSuchFieldError: Class org.bukkit.entity.EntityType does not have member field 'org.bukkit.entity.EntityType ENDER_CRYSTAL'
        at combatlogx.expansion.endcrystals.ListenerCrystals_Modern.onPlace(ListenerCrystals_Modern.java:32) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor364.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityPlaceEvent(CraftEventFactory.java:502) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityPlaceEvent(CraftEventFactory.java:493) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.world.item.EndCrystalItem.useOn(EndCrystalItem.java:51) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:434) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:603) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1942) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]"

### Reproduction Steps

1. Install CombatLogX + Endcrystal Helper
2. Place a End Crystal

### Expected behaviour

An error will displayed in the console

### CombatLogX Version

[12:36:52 INFO]: Java Version: 21.0.3
[12:36:52 INFO]: Java Vendor: Eclipse Adoptium
[12:36:52 INFO]: Java URL: N/A
[12:36:52 INFO]: Server Version: 1.21.1-119-7cd4f2c (MC: 1.21.1)
[12:36:52 INFO]: Bukkit Version: 1.21.1-R0.1-SNAPSHOT
[12:36:52 INFO]: Minecraft Version: 1.21.1
[12:36:52 INFO]: NMS Version: Unsupported
[12:36:52 INFO]: Dependency Information:
[12:36:52 INFO]:  - AngelChest (not installed)
[12:36:52 INFO]:  - ASkyBlock (not installed)
[12:36:52 INFO]:  - BentoBox (not installed)
[12:36:52 INFO]:  - Citizens (not installed)
[12:36:52 INFO]:  - CMI (not installed)
[12:36:52 INFO]:  - CrackShot (not installed)
[12:36:52 INFO]:  - CrashClaim (not installed)
[12:36:52 INFO]:  - Essentials (not installed)
[12:36:52 INFO]:  - FabledSkyBlock (not installed)
[12:36:52 INFO]:  - FeatherBoard (not installed)
[12:36:52 INFO]:  - FlagWar (not installed)
[12:36:52 INFO]:  - GriefDefender (not installed)
[12:36:52 INFO]:  - GriefPrevention (not installed)
[12:36:52 INFO]:  - HuskHomes (not installed)
[12:36:52 INFO]:  - HuskSync (not installed)
[12:36:52 INFO]:  - HuskTowns (not installed)
[12:36:52 INFO]:  - iDisguise (not installed)
[12:36:52 INFO]:  - IridiumSkyblock (not installed)
[12:36:52 INFO]:  - Kingdoms (not installed)
[12:36:52 INFO]:  - Konquest (not installed)
[12:36:52 INFO]:  - Lands v7.10.7
[12:36:52 INFO]:  - LibsDisguises (not installed)
[12:36:52 INFO]:  - MarriageMaster (not installed)
[12:36:52 INFO]:  - MCPets (not installed)
[12:36:52 INFO]:  - MythicMobs (not installed)
[12:36:52 INFO]:  - PlaceholderAPI v2.11.6
[12:36:52 INFO]:  - PlayerParticles (not installed)
[12:36:52 INFO]:  - PreciousStones (not installed)
[12:36:52 INFO]:  - PremiumVanish (not installed)
[12:36:52 INFO]:  - ProtectionStones (not installed)
[12:36:52 INFO]:  - ProtocolLib v5.3.0-SNAPSHOT-732
[12:36:52 INFO]:  - RedProtect (not installed)
[12:36:52 INFO]:  - Residence (not installed)
[12:36:52 INFO]:  - Sentinel (not installed)
[12:36:52 INFO]:  - SuperiorSkyblock2 (not installed)
[12:36:52 INFO]:  - SuperVanish (not installed)
[12:36:52 INFO]:  - Towny (not installed)
[12:36:52 INFO]:  - UltimateClaims (not installed)
[12:36:52 INFO]:  - uSkyBlock (not installed)
[12:36:52 INFO]:  - VanishNoPacket (not installed)
[12:36:52 INFO]:  - WorldGuard v7.0.12+829a4a4
[12:36:52 INFO]:  - ViaVersion (not installed)
[12:36:52 INFO]:  - BlueSlimeCore v2.9.6.431
[12:36:52 INFO]: CombatLogX by SirBlobman
[12:36:52 INFO]: Local Version: 11.5.0.0.1242
[12:36:52 INFO]: Remote Version: 11.5.0.0.1242
[12:36:52 INFO]: Enabled Expansions (6):
[12:36:52 INFO]:  - Action Bar v17.3
[12:36:52 INFO]:  - Cheat Prevention v17.7
[12:36:52 INFO]:  - PlaceholderAPI Compatibility v17.2
[12:36:52 INFO]:  - End Crystal Helper v17.1
[12:36:52 INFO]:  - Glowing v17.0
[12:36:52 INFO]:  - Newbie Helper v17.2

**Comment by Olivoz** [comment]
This issue should already be fixed in the latest beta builds available on the [jenkins](https://jenkins.sirblobman.xyz/job/SirBlobman/job/CombatLogX/job/main/).

**Comment by wchtig** [comment]
Which one exactly? Because the latest build failed ig.

**Comment by Olivoz** [comment]
Grab the latest successful build (1257). You can find it under `Last Successful Artifacts` or on the left hand side of the page

**Comment by wchtig** [comment]
I already tried the lates succesfull build. But also this one produces an error. (the same)
"[14:05:34 INFO]: CombatLogX by SirBlobman
[14:05:34 INFO]: Local Version: 11.5.0.0.1257
[14:05:34 INFO]: Remote Version: 11.5.0.0.1242
[14:05:34 INFO]: Enabled Expansions (6):
[14:05:34 INFO]:  - Action Bar v17.3
[14:05:34 INFO]:  - Cheat Prevention v17.7
[14:05:34 INFO]:  - PlaceholderAPI Compatibility v17.2
[14:05:34 INFO]:  - End Crystal Helper v17.1
[14:05:34 INFO]:  - Glowing v17.0
[14:05:34 INFO]:  - Newbie Helper v17.2"

**Comment by Olivoz** [comment]
Looks like you did not update the expansions

**Comment by wchtig** [comment]
Yes... I forgot to update the expansions. Ty. Now it works perfect <3
